const menuToggle = document.querySelector('.menu-toggle');
const nav = document.querySelector('.global-nav');
if (menuToggle && nav) {
  menuToggle.addEventListener('click', () => nav.classList.toggle('open'));
  nav.querySelectorAll('a:not(.nav-parent)').forEach(link => link.addEventListener('click', () => nav.classList.remove('open')));
}
document.querySelectorAll('[data-dropdown]').forEach(dropdown => {
  const button = dropdown.querySelector('.nav-parent');
  if (!button) return;

  button.addEventListener('click', event => {
    if (window.matchMedia('(max-width: 780px)').matches) {
      event.preventDefault();
    }
    event.stopPropagation();
    const isOpen = dropdown.classList.toggle('open');
    button.setAttribute('aria-expanded', String(isOpen));
  });

  dropdown.querySelectorAll('a:not(.nav-parent)').forEach(link => {
    link.addEventListener('click', () => {
      dropdown.classList.remove('open');
      button.setAttribute('aria-expanded', 'false');
    });
  });
});
document.addEventListener('click', () => {
  document.querySelectorAll('[data-dropdown].open').forEach(dropdown => {
    dropdown.classList.remove('open');
    const button = dropdown.querySelector('.nav-parent');
    if (button) button.setAttribute('aria-expanded', 'false');
  });
});
document.querySelectorAll('[data-tabs]').forEach(tabGroup => {
  const buttons = tabGroup.querySelectorAll('.tab-btn');
  const panels = tabGroup.querySelectorAll('.tab-panel');
  buttons.forEach(button => {
    button.addEventListener('click', () => {
      const target = button.dataset.tab;
      buttons.forEach(btn => btn.classList.remove('active'));
      panels.forEach(panel => panel.classList.remove('active'));
      button.classList.add('active');
      const activePanel = tabGroup.querySelector(`#${target}`);
      if (activePanel) activePanel.classList.add('active');
    });
  });
});
document.querySelectorAll('[data-accordion] .accordion-header').forEach(header => {
  header.addEventListener('click', () => header.parentElement.classList.toggle('open'));
});

const translations = {
  en: {
    '2026 데상트 어웨이큰 에키덴 레이스': '2026 Descente Awaken Ekiden Race',
    '2026 데상트 어웨이큰 에키덴 레이스 참가자 안내 홈페이지': 'Official participant information site for the 2026 Descente Awaken Ekiden Race',
    '2026 데상트 어웨이큰 에키덴 레이스 참고용 페이지(비공식)': '2026 Descente Awaken Ekiden Race reference page (unofficial)',
    '데상트 에키덴 레이스': 'Descente Ekiden Race',
    '데상트 러닝 커뮤니티': 'Descente Running Community',
    '참가 안내': 'Entry Guide',
    '레이스 운영': 'Race Operations',
    '대회 코스': 'Race Course',
    '규정': 'Rules',
    '시간표': 'Schedule',
    '유의 사항': 'Important Notes',
    '맨 위로': 'Back to top',
    '데상트 어웨이큰 에키덴 레이스는 에키덴에서 영감을 받은 팀 릴레이 레이스입니다. 개인의 기록보다 함께 달리는 가치에 집중하며, 러너 간의 팀워크와 열정을 극대화하는 데 초점을 맞췄습니다.': 'The Descente Awaken Ekiden Race is a team relay event inspired by the spirit of ekiden. Rather than focusing solely on individual records, the event celebrates the value of running together and highlights teamwork, energy, and connection among runners.',
    '한 사람의 움직임이 다음 주자에게 이어지고, 각자의 힘이 하나의 흐름으로 완성되는 순간. 이 레이스는 함께 달리고, 연결됨을 느끼며, 한계를 넘어 깨어나는 경험을 만들어갑니다.': 'As one runner’s effort carries forward to the next, individual strengths become one continuous flow. This race is designed to create a shared experience of movement, connection, and awakening beyond personal limits.',
    '대회명': 'Event name',
    '개최일': 'Event dates',
    '장소': 'Venue',
    '주최/주관': 'Host / Organizer',
    '전쟁기념관 지하 주차장': 'War Memorial underground parking area',
    '데상트(DESCENTE)': 'Descente (DESCENTE)',
    'Race Information': 'Race Information',
    '대회 안내': 'Race Information',
    '대회 기본 정보': 'Event Overview',
    'Race Entry': 'Race Entry',
    '참가 부문 안내': 'Race Division Guide',
    '운영일': 'Event date',
    '일반 참가 부문': 'General Entry',
    '크루 초청 부문': 'Crew Invitational',
    '2026년 6월 22일(월)': 'June 22 (Mon), 2026',
    '2026년 6월 23일(화)': 'June 23 (Tue), 2026',
    '참가 규모': 'Entry size',
    '최대 162명, 총 9개 크루': 'Up to 162 participants, 9 crews in total',
    '레이스 구성': 'Race categories',
    '남자 2인 릴레이, 여자 2인 릴레이, 혼성 4인 릴레이': 'Men’s 2-Person Relay, Women’s 2-Person Relay, Mixed 4-Person Relay',
    '개인전, 3인 릴레이, 혼성 4인 릴레이, 혼성 6인 릴레이': 'Individual, 3-Person Relay, Mixed 4-Person Relay, Mixed 6-Person Relay',
    '진행 방식': 'Race format',
    '기록 순위로 순위를 산정하는 타임트라이얼 방식': 'Time-trial format with rankings determined by official time',
    '예선과 결선으로 운영되는 순위 경쟁 방식': 'Placement-based format operated through preliminary and final rounds',
    '각 부문 기록 순위에 따라 팀 전원에게 리워드 지급': 'Awards provided to all eligible team members according to official time rankings by category',
    '부문별 우승팀 및 종합 포인트 상위 크루 대상 리워드 지급': 'Awards provided to category winners and top crews in the overall point ranking',
    '대회 접수 안내 보기': 'View Entry Guide',
    '레이스 운영 보기': 'View Race Operations',
    '대회 접수 안내': 'Race Entry Guide',
    '6월 22일(월) | 일반 참가 접수 부문': 'June 22 (Mon) | General Entry',
    '6월 23일(화) | 크루 초청 부문': 'June 23 (Tue) | Crew Invitational',
    '신청 기간': 'Application period',
    '참가 인원': 'Participants',
    '참가 대상': 'Eligibility',
    '진행 시간': 'Event time',
    '참가 방식': 'Entry process',
    '선정 발표': 'Selection announcement',
    '참가 패키지': 'Participant package',
    '2026년 5월 11일(월) ~ 5월 25일(월)': 'May 11 (Mon) - May 25 (Mon), 2026',
    '240명': '240 participants',
    '만 19세 이상 일반 러너': 'General runners aged 19 or older',
    '6월 22일(월) 오후 7시 50분 ~ 오후 10시 (체크인: 오후 7시)': 'June 22 (Mon), 7:50 PM - 10:00 PM (check-in: 7:00 PM)',
    '신청 기간 내 참가 신청을 접수한 뒤, 운영 기준에 따라 참가팀을 선정합니다.': 'Applications will be reviewed after the application period, and participating teams will be selected in accordance with the event operation criteria.',
    '2026년 6월 5일(금) 오후 6시, 선정자 대상 문자 안내': 'Selected participants will be notified by text message at 6:00 PM on Friday, June 5, 2026.',
    '기념 반팔 티셔츠, 기록 측정용 배번호': 'Commemorative short-sleeve T-shirt and timing bib',
    '신청 정보 입력 항목': 'Application Information Fields',
    '신청 방법': 'How to Apply',
    '데상트 공식 홈페이지 접속': 'Visit the official DESCENTE website',
    '레이스 페이지 확인': 'Check the race page',
    '팀 단위 신청': 'Apply as a team',
    '팀원 전원 개별 신청 완료': 'All team members complete individual applications',
    '참가자 발표 확인': 'Check participant announcement',
    '어웨이큰 에키덴 레이스 및 데상트 러닝 커뮤니티 페이지 확인': 'Check the Awaken Ekiden Race and Descente Running Community pages',
    '참여를 희망하는 DRC 프로그램 신청': 'Apply for the DRC program you want to join',
    '신청 완료': 'Complete application',
    '최종 참가자 발표 확인': 'Check final participant announcement',
    '데상트 공식 홈페이지 접속 → 어웨이큰 에키덴 레이스 및 데상트 러닝 커뮤니티 페이지 확인 → 참여를 희망하는 DRC 프로그램 신청 → 신청 완료 → 최종 참가자 발표 확인': 'Visit the official DESCENTE website -> Check the Awaken Ekiden Race and Descente Running Community pages -> Apply for the DRC program you want to join -> Complete application -> Check final participant announcement',
    'DRC는 크루원과 게스트 모두 데상트 공식 홈페이지를 통해 직접 신청해야 하며, 신청 완료 후 최종 참가자 발표를 통해 참가 여부가 확정됩니다.': 'Both crew members and guests must apply directly through the official DESCENTE website for DRC, and participation will be confirmed through the final participant announcement after application is completed.',
    '데상트 공식 홈페이지 접속 → 레이스 페이지 확인 → 팀 단위 신청 → 팀원 전원 개별 신청 완료 → 참가자 발표 확인': 'Visit the official DESCENTE website -> Check the race page -> Apply as a team -> All team members complete individual applications -> Check participant announcement',
    '일반 참가 부문은 데상트 공식 홈페이지 내 어웨이큰 에키덴 레이스 페이지를 통해 신청할 수 있습니다. 참가를 원하는 팀은 신청 페이지에서 참가 부문을 확인한 뒤 팀 단위로 신청을 진행해야 하며, 팀 구성원 전원이 각각 신청을 완료해야 정상 접수로 인정됩니다. 신청 완료 후에는 참가자 발표 일정에 맞춰 최종 선정 여부를 확인할 수 있습니다.': 'The General Entry division can be applied for through the Awaken Ekiden Race page on the official DESCENTE website. Teams wishing to participate must check the applicable race category on the application page and proceed with a team-based application, and all team members must each complete their own application for the entry to be considered valid. After applying, teams can check whether they were selected according to the participant announcement schedule.',
    '크루별 별도 안내': 'Receive separate crew guidance',
    '참가 부문 확인': 'Check participation category',
    '별도 신청폼 작성': 'Fill out the separate application form',
    '운영 안내 확인': 'Review event operations guidance',
    '크루별 별도 안내 → 참가 부문 확인 → 별도 신청폼 작성 → 신청 완료 → 운영 안내 확인': 'Receive separate crew guidance -> Check participation category -> Fill out the separate application form -> Complete application -> Review event operations guidance',
    '크루 초청 부문은 사전 초청된 크루를 대상으로 별도 안내할 예정입니다. 각 크루는 전달받은 안내에 따라 참가 가능 부문과 인원을 확인한 뒤, 별도 신청폼을 통해 참가 신청을 진행합니다. 신청 완료 후에는 대회 운영과 관련한 세부 사항을 별도로 안내받게 됩니다.': 'The Crew Invitational division will be guided separately for pre-invited crews. Each crew will confirm its eligible categories and participant count according to the guidance received, then submit its application through a separate application form. After completing the application, each crew will receive additional details related to event operations.',
    '입력 항목': 'Field',
    '내용': 'Details',
    '대표자 이름': 'Representative name',
    '팀 대표자 성명': 'Team representative full name',
    '휴대폰 번호 뒷자리': 'Last four digits of mobile number',
    '본인 확인 및 참가자 식별용': 'For identity verification and participant identification',
    '팀명': 'Team name',
    '참가 팀명': 'Participating team name',
    '나에게 러닝이란?': 'What does running mean to me?',
    '신청자 스토리 및 선발 참고 문항': 'Applicant statement used as reference for selection',
    '2026년 4월 24일(금) ~ 5월 3일(일)': 'April 24 (Fri) - May 3 (Sun), 2026',
    '최대 162명': 'Up to 162 participants',
    '초청 크루': 'Invited crews',
    '6월 23일(화) 오후 7시 50분 ~ 오후 10시 (체크인: 오후 7시)': 'June 23 (Tue), 7:50 PM - 10:00 PM (check-in: 7:00 PM)',
    '브랜드 초청 크루 총 9개 팀 운영': 'The division will be operated with a total of 9 crews invited by the brand.',
    '해당 없음': 'Not applicable',
    '대회 기념 긴팔 티셔츠, 크루 싱글렛, 하프 타이츠, 델타프로 EXP V3, 기록 측정용 배번호': 'Commemorative long-sleeve T-shirt, crew singlet, half tights, DELTAPRO EXP V3, and timing bib',
    '참가 신청': 'Apply',
    '일반 참가 부문': 'General Entry',
    '크루 초청 부문': 'Crew Invitational',
    '일반 참가 부문 | 2026년 6월 22일(월)': 'General Entry | June 22 (Mon), 2026',
    '크루 초청 부문 | 2026년 6월 23일(화)': 'Crew Invitational | June 23 (Tue), 2026',
    '레이스 부문': 'Race Categories',
    '부문': 'Category',
    '모집 규모': 'Capacity',
    '남자 2인 릴레이': 'Men’s 2-person Relay',
    '여자 2인 릴레이': 'Women’s 2-person Relay',
    '혼성 4인 릴레이': 'Mixed 4-person Relay',
    '남자부 개인전': 'Men’s Individual',
    '여자부 개인전': 'Women’s Individual',
    '남자부 3인 릴레이': 'Men’s 3-person Relay',
    '여자부 3인 릴레이': 'Women’s 3-person Relay',
    '혼성 6인 릴레이': 'Mixed 6-person Relay',
    '개인전': 'Individual',
    '3인 릴레이': '3-person Relay',
    '혼성 릴레이': 'Mixed Relay',
    '구분': 'Type',
    '남자부 개인전여자부 개인전': 'Men’s Individual / Women’s Individual',
    '남자부 3인 릴레이여자부 3인 릴레이': 'Men’s 3-person Relay / Women’s 3-person Relay',
    '혼성 4인 릴레이혼성 6인 릴레이': 'Mixed 4-person Relay / Mixed 6-person Relay',
    '40팀': '40 teams',
    '20팀': '20 teams',
    '레이스 방식': 'Race Format',
    '일반 참가 부문은 타임트라이얼 방식으로 진행됩니다.': 'The General Entry division will be conducted in a time-trial format.',
    '각 팀은 기록 측정용 배번호를 통해 기록이 측정됩니다.': 'Each team’s official time will be measured using the assigned timing bib.',
    '순위는 각 레이스 부문별 기록 순위에 따라 결정됩니다.': 'Rankings will be determined by official time within each race category.',
    '복장 규정': 'Dress Code',
    '어웨이큰 에키덴 레이스는 참가자 모두가 동일한 조건에서 레이스를 경험하고 경쟁할 수 있도록 운영하는 것을 기본 원칙으로 한다. 따라서 부문별로 주최측이 지정한 의류와 신발을 반드시 착용해야 하며, 이를 통해 경기의 공정성과 대회 콘셉트의 일관성을 함께 확보하고자 한다.': 'The Awaken Ekiden Race is operated on the core principle that all participants should experience and compete under the same conditions. Accordingly, participants must wear the clothing and shoes designated by the organizer for each division in order to ensure both competitive fairness and consistency with the event concept.',
    '즉, 이번 대회는 단순한 자유 복장 러닝 이벤트가 아니라, 동일한 퍼포먼스 환경 안에서 레이스를 진행하는 것이 핵심 규정이다.': 'In other words, this event is not simply a free-dress running event. A core rule is that the race is conducted within the same performance environment for everyone.',
    '의무 착용 항목': 'Mandatory Items',
    '대회 패키지로 제공되는 대회 기념 반팔 티셔츠': 'Official commemorative short-sleeve T-shirt included in the race package',
    '주최측이 제공하는 트라이얼용 델타프로 EXP V3': 'Trial DELTAPRO EXP V3 provided by the organizer',
    '자유 착용 가능 항목': 'Optional Items',
    '하의, 양말은 자유롭게 착용 가능': 'Bottoms and socks may be worn freely',
    '부문별 리워드': 'Category Awards',
    '남자/여자부 개인전': 'Men’s/Women’s Individual',
    '남자/여자부 3인 릴레이': 'Men’s/Women’s 3-Person Relay',
    '순위': 'Rank',
    '1위': '1st place',
    '2026 JTBC 서울마라톤 티켓': '2026 JTBC Seoul Marathon ticket',
    '2026 JTBC 서울마라톤 티켓 전원 지급': '2026 JTBC Seoul Marathon ticket for all team members',
    '기록 순위': 'Official time ranking',
    '리워드': 'Reward',
    '1위~3위 팀': '1st-3rd place teams',
    '4위~6위 팀': '4th-6th place teams',
    '7위~10위 팀': '7th-10th place teams',
    '1위~5위 팀': '1st-5th place teams',
    '6위~10위 팀': '6th-10th place teams',
    '11위~15위 팀': '11th-15th place teams',
    '남자/여자 2인 릴레이': 'Men’s/Women’s 2-Person Relay',
    '혼성 4인 릴레이': 'Mixed 4-Person Relay',
    '2026 JTBC 서울마라톤 티켓 + 델타프로 EXP V3': '2026 JTBC Seoul Marathon ticket + DELTAPRO EXP V3',
    '2026 JTBC 서울마라톤 티켓 + 델타프로 ADV V2': '2026 JTBC Seoul Marathon ticket + DELTAPRO ADV V2',
    '델타프로 ADV V2': 'DELTAPRO ADV V2',
    '각 레이스 부문에서 기록 순위에 따라 리워드가 제공되며, 해당 순위 팀 전원에게 지급됩니다.': 'Awards will be provided according to the official time ranking in each race category and will be awarded to all members of the eligible teams.',
    '안내 사항': 'Additional Information',
    '참가자 편의를 위해 대회장 내에 산업용 이동식 에어컨을 설치할 예정입니다.': 'For participant comfort, industrial portable air conditioners will be installed at the event venue.',
    '일반 참가 부문과 크루 초청 부문 간 중복 참가는 불가합니다.': 'Duplicate participation across the General Entry and Crew Invitational divisions is not permitted.',
    '레이스 부문별 토너먼트 조 추첨은 5월 9일(토, 예정) 온라인 또는 오프라인으로 진행할 예정입니다.': 'The tournament group draw for each race category is scheduled to take place on Saturday, May 9, either online or offline.',
    '대회 규정은 조 추첨 당일 운영진 회의를 통해 상세히 안내할 예정이며, 필요 시 대회 전까지 일부 내용을 수정·보완할 수 있습니다.': 'Detailed race regulations will be explained during the organizers meeting on the day of the group draw, and some details may be revised or supplemented before the event if necessary.',
    '일반 참가 부문 리워드로 제공되는 JTBC 서울마라톤 티켓은 타인에게 양도할 수 없습니다.': 'JTBC Seoul Marathon tickets provided as rewards in the General Entry division are non-transferable.',
    '순위는 남자 2인 릴레이 / 여자 2인 릴레이 / 혼성 4인 릴레이 각 부문별로 별도 산정됩니다.': 'Rankings will be calculated separately for the Men’s 2-Person Relay, Women’s 2-Person Relay, and Mixed 4-Person Relay categories.',
    '기록 측정용 배번호는 대회 당일 반드시 지정된 방식으로 착용해야 합니다.': 'Timing bibs must be worn in the designated manner on race day.',
    '혼성 4인 릴레이 구성은 남자 2인 + 여자 2인입니다.': 'The mixed 4-person relay consists of 2 men and 2 women.',
    '혼성 릴레이 구성': 'Mixed Relay Composition',
    '남자 2인 + 여자 2인': '2 men + 2 women',
    '남자 3인 + 여자 3인': '3 men + 3 women',
    '크루 초청 부문은 예선 - 결선 방식으로 진행됩니다.': 'The Crew Invitational division will be conducted through preliminary and final rounds.',
    '총 9개 크루가 참가하며, 3개 크루씩 1개 조로 예선을 진행합니다.': 'A total of 9 crews will participate, with preliminary heats organized into groups of 3 crews.',
    '각 부문은 총 3개 조로 운영되며, 각 조 1위 팀만 결선에 진출합니다.': 'Each category will consist of 3 groups, and only the top team from each group will advance to the final.',
    '따라서 모든 부문은 결선 3팀 동일 구조로 운영됩니다.': 'Accordingly, every category will follow the same final-round structure of 3 teams.',
    '토너먼트 대진표': 'Tournament Bracket',
    '예선': 'Preliminary',
    '3개 크루 참가': '3 crews compete',
    '1위 팀 결선 진출': '1st-place team advances to the final',
    '결선': 'Final',
    '결선 3팀': '3 teams in the final',
    '1조 1위': 'Group 1 winner',
    '2조 1위': 'Group 2 winner',
    '3조 1위': 'Group 3 winner',
    '최종 순위 결정': 'Final standings decided',
    '주최측이 제공하는 크루 싱글렛': 'Crew singlet provided by the organizer',
    '주최측이 제공하는 하프 타이즈': 'Half tights provided by the organizer',
    '주최측이 제공하는 델타프로 EXP V3': 'DELTAPRO EXP V3 provided by the organizer',
    '양말은 자유롭게 착용 가능': 'Socks may be worn freely',
    '크루 초청 부문 종합 포인트 운영안': 'Crew Invitational Overall Point System',
    '결선 순위': 'Final ranking',
    '부여 포인트': 'Points awarded',
    '1위': '1st',
    '2위': '2nd',
    '3위': '3rd',
    '10 포인트': '10 points',
    '6 포인트': '6 points',
    '3 포인트': '3 points',
    '각 레이스 부문 결선 결과 기준으로 1~3위 크루에 포인트를 부여합니다.': 'Points are awarded to the 1st-3rd place crews based on final results in each race category.',
    '포인트 집계 대상 부문': 'Point-Scoring Categories',
    '대상 부문': 'Target category',
    '남자 개인전여자 개인전': 'Men’s Individual / Women’s Individual',
    '남자 3인 릴레이여자 3인 릴레이': 'Men’s 3-person Relay / Women’s 3-person Relay',
    '총 6개 부문 점수를 합산해 종합 순위를 산정합니다.': 'Overall rankings will be calculated by combining points from all 6 categories.',
    '최종 리워드': 'Overall Awards',
    '종합 우승 크루': 'Overall winning crew',
    '종합 준우승 크루': 'Overall runner-up crew',
    'JTBC 서울마라톤 티켓 8장': '8 JTBC Seoul Marathon tickets',
    'JTBC 서울마라톤 티켓 5장': '5 JTBC Seoul Marathon tickets',
    '동점 처리 기준': 'Tie-Break Rules',
    '포인트 합산 결과가 같을 경우 아래 기준 순으로 최종 순위를 결정합니다.': 'In the event of a tie in total points, final ranking will be determined in the following order.',
    '부문별 1위 횟수가 많은 크루 우선': 'Crew with more category wins takes priority.',
    '혼성 6인 릴레이 순위가 높은 크루 우선': 'Crew with the higher mixed 6-person relay ranking takes priority.',
    '즉, 종합 포인트가 같더라도 더 많은 부문에서 우승한 크루가 우선이며, 1위 횟수까지 같을 경우에는 마지막 메인 종목인 혼성 6인 릴레이 성적이 높은 크루가 최종 상위 순위를 차지합니다.': 'In short, even if total points are tied, the crew with more category wins ranks higher. If the number of wins is also tied, the crew with the better result in the final main event, the mixed 6-person relay, ranks higher.',
    '출전 유의사항': 'Participation Notes',
    '남자부/여자부 개인전과 남자부/여자부 3인 릴레이는 같은 참가자가 중복 출전할 수 없습니다.': 'The same participant may not enter both the men’s/women’s individual race and the men’s/women’s 3-person relay.',
    '혼성 릴레이는 개인전 또는 3인 릴레이 출전자가 추가로 1개 부문까지 중복 출전할 수 있습니다.': 'Participants in the individual or 3-person relay may additionally enter up to one mixed relay category.',
    '단, 1인이 3개 이상 부문에 출전하는 것은 불가합니다.': 'However, one person may not enter three or more categories.',
    '운영 시간표': 'Event Schedule',
    'Day 1 | 일반 참가': 'Day 1 | General Entry',
    'Day 2 | 크루 초청': 'Day 2 | Crew Invitational',
    '시간': 'Time',
    '비고': 'Notes',
    '체크인': 'Check-in',
    '배번 수령, 신분 확인, 선수 대기 안내': 'Bib pickup, ID check, athlete waiting guidance',
    '오프닝 및 경기 브리핑': 'Opening and race briefing',
    '경기 방식, 코스, 인계 구역, 리워드 안내': 'Race format, course, handoff zone, and rewards briefing',
    '크루 소개, 경기 방식, 포인트 규정 안내': 'Crew introduction, race format, and point rules briefing',
    '10회차 / 4팀 동시 출발': '10 waves / 4 teams start together',
    '5회차 / 4팀 동시 출발': '5 waves / 4 teams start together',
    '시상식': 'Awards ceremony',
    '1~15위 팀 시상 및 촬영': 'Awards and photos for 1st-15th place teams',
    '부문 시상 + 종합 시상': 'Category awards + overall awards',
    '개인전 및 3인 릴레이 예선': 'Individual and 3-person relay preliminaries',
    '개인전 및 3인 릴레이 결선': 'Individual and 3-person relay finals',
    '혼성 릴레이 예선': 'Mixed relay preliminaries',
    '혼성 릴레이 결선': 'Mixed relay finals',
    '3개 조 운영': 'Operated in 3 groups',
    '조별 1위 진출': 'Group winners advance',
    '혼성 4인 / 혼성 6인': 'Mixed 4-person / mixed 6-person',
    '회차': 'Wave',
    '조': 'Group',
    '운영 정보': 'Operational Details',
    '1회차당 4팀 출발': '4 teams start per wave',
    '남자 2인 릴레이 상세 시간표': 'Men’s 2-person Relay Detailed Schedule',
    '여자 2인 릴레이 상세 시간표': 'Women’s 2-person Relay Detailed Schedule',
    '혼성 4인 릴레이 상세 시간표': 'Mixed 4-person Relay Detailed Schedule',
    '남자 개인전 예선 상세 시간표': 'Men’s Individual Preliminary Detailed Schedule',
    '여자 개인전 예선 상세 시간표': 'Women’s Individual Preliminary Detailed Schedule',
    '남자 3인 릴레이 예선 상세 시간표': 'Men’s 3-person Relay Preliminary Detailed Schedule',
    '여자 3인 릴레이 예선 상세 시간표': 'Women’s 3-person Relay Preliminary Detailed Schedule',
    '개인전 및 3인 릴레이 결선 상세 시간표': 'Individual and 3-person Relay Finals Detailed Schedule',
    '혼성 4인 릴레이 예선 상세 시간표': 'Mixed 4-person Relay Preliminary Detailed Schedule',
    '혼성 6인 릴레이 예선 상세 시간표': 'Mixed 6-person Relay Preliminary Detailed Schedule',
    '혼성 릴레이 결선 상세 시간표': 'Mixed Relay Finals Detailed Schedule',
    '예선 1조': 'Preliminary Group 1',
    '예선 2조': 'Preliminary Group 2',
    '예선 3조': 'Preliminary Group 3',
    '결선': 'Final',
    '남자 개인전 예선': 'Men’s Individual Preliminary',
    '여자 개인전 예선': 'Women’s Individual Preliminary',
    '남자 3인 릴레이 예선': 'Men’s 3-person Relay Preliminary',
    '여자 3인 릴레이 예선': 'Women’s 3-person Relay Preliminary',
    '혼성 4인 릴레이 예선': 'Mixed 4-person Relay Preliminary',
    '혼성 6인 릴레이 예선': 'Mixed 6-person Relay Preliminary',
    '남자 개인전 결선': 'Men’s Individual Final',
    '여자 개인전 결선': 'Women’s Individual Final',
    '남자 3인 릴레이 결선': 'Men’s 3-person Relay Final',
    '여자 3인 릴레이 결선': 'Women’s 3-person Relay Final',
    '혼성 4인 릴레이 결선': 'Mixed 4-person Relay Final',
    '혼성 6인 릴레이 결선': 'Mixed 6-person Relay Final',
    '대회 개요': 'Event Overview',
    '참가비': 'Entry fee',
    '무료': 'Free',
    '300m 길이의 8자 형태 코스로 운영': 'Operated on a 300m figure-eight course',
    '코스 이미지는 추후 업데이트 예정': 'Course map to be updated.',
    '데상트 러닝 커뮤니티 (DRC)': 'Descente Running Community (DRC)',
    '데상트 러닝 커뮤니티(DRC)는 함께 달리고, 경험을 나누며, 러닝을 일상으로 만드는 커뮤니티입니다. 대회 전 약 8주간 크루별 호스트 프로그램과 일반 러너 참여 방식으로 운영됩니다.': 'Descente Running Community (DRC) is a running community built around shared movement, experience, and everyday running culture. For approximately 8 weeks leading up to the race, DRC will operate through crew-hosted programs and participation opportunities for general runners.',
    '운영 기간': 'Operating period',
    '운영 횟수': 'Number of sessions',
    '공통 제공': 'Provided for all sessions',
    '5월 3주차 ~ 6월 3주차': '3rd week of May - 3rd week of June',
    '총 8회': '8 sessions total',
    '슈즈 트라이얼, F&B, 짐보관': 'Shoe trial, F&B, bag storage',
    '프로그램명': 'Program',
    '진행일': 'Date',
    '집결지': 'Meeting point',
    '특징': 'Feature',
    '업데이트 예정': 'To be updated',
    '시티 트레일 러닝': 'City trail running',
    '시티런 & 커피런': 'City run & coffee run',
    '반포종합운동장 7K 인터벌': 'Banpo Sports Complex 7K intervals',
    '커피런 + 이벤트': 'Coffee run + event',
    '그룹 릴레이 레이스': 'Group relay race',
    '버거런': 'Burger run',
    '빙고런': 'Bingo run',
    '시티 & 한강 러닝': 'City & Han River running',
    '레이스 규정': 'Race Rules',
    '운영 원칙': 'Operating Principles',
    '경기 방식': 'Race Format',
    '코스 규정': 'Course Rules',
    '인계 규정': 'Handoff Rules',
    '선수 확인': 'Athlete Check',
    '출발/진행': 'Start / Race Flow',
    '실격 사유': 'Disqualification',
    '판정/이의': 'Judging / Appeals',
    '1. 운영 기본 원칙': '1. Basic Operating Principles',
    '2. 경기 방식 및 순위 산정': '2. Race Format and Ranking Criteria',
    '3. 대회 코스 규정': '3. Course Rules',
    '4. 바통(어깨끈 포함) 인계 규정': '4. Baton / Shoulder-Strap Handoff Rules',
    '5. 선수 확인 및 대기 규정': '5. Athlete Verification and Waiting Area Rules',
    '6. 출발 및 진행 규정': '6. Start and Race Conduct Rules',
    '7. 실격 및 기록 불인정 사유': '7. Disqualification and Record Invalidation Grounds',
    '8. 판정 및 이의 제기': '8. Judging and Appeals',
    '본 대회는 일반 참가 부문과 크루 초청 부문으로 나누어 운영하며, 각 부문별 경기 방식과 순위 산정 기준은 아래와 같습니다.': 'This event will be operated in two divisions: General Entry and Crew Invitational. The race format and ranking criteria for each division are outlined below.',
    '기록 측정 배번 기준으로 기록을 산정하여 순위를 결정': 'Rankings will be determined based on records measured through timing bibs.',
    '결승선 통과 순서 기준으로 순위를 결정': 'Rankings will be determined based on the order of finish-line crossing.',
    '모든 참가자는 대회 운영진 및 심판의 안내에 따라 경기해야 하며, 정해진 코스와 규정을 준수하지 않을 경우 기록 인정이 제한되거나 실격 처리될 수 있습니다.': 'All participants must follow the instructions of event staff and judges. Failure to follow the designated course or event rules may result in record invalidation or disqualification.',
    '기록 측정 원칙': 'Timing Principles',
    '일반 참가 부문은 기록 경쟁형 릴레이 레이스로 운영합니다. 각 팀의 최종 순위는 기록 측정 배번을 통해 측정된 공식 기록을 기준으로 산정합니다.': 'The General Entry division will be conducted as a time-based relay race. Each team’s final ranking will be calculated based on the official record measured through its timing bib.',
    '공식 기록은 기록 측정 배번을 통해 자동 집계된 기록을 기준으로 합니다.': 'Official records will be based on the times automatically collected through timing bibs.',
    '각 팀의 최종 순위는 해당 부문의 전체 참가팀 기록을 일괄 비교하여 결정합니다.': 'Final rankings will be determined by comparing all team records within the relevant category.',
    '경기 중 같은 레이스에 여러 팀이 동시에 출발하더라도, 최종 순위는 결승선 통과 순서가 아니라 공식 기록 기준으로 결정합니다.': 'Even if multiple teams start the same race together, final ranking is determined by official time, not by finish-line order.',
    '예외 상황': 'Exceptions',
    '기록 측정 배번에 오류가 발생하거나 계측 데이터 확인이 어려운 경우를 대비해, 대회장 내 심판은 육상대회용 초시계(스톱워치)로 별도 기록을 측정하고 수기로 기록합니다.': 'To prepare for timing bib errors or cases where timing data cannot be verified, on-site judges will separately measure and record times manually using athletics stopwatches.',
    '수기 기록은 기본적으로 참고 기록으로 사용합니다.': 'Manual records will generally be used as reference records.',
    '다만 기록 측정 배번 오류 등 공식 계측이 불가능한 경우에는 운영본부 및 심판진 확인을 거쳐 수기 기록을 보조 기준으로 활용할 수 있습니다.': 'If official timing is not possible due to timing bib errors or similar issues, manual records may be used as a supplementary standard after review by event headquarters and judges.',
    '크루 초청 부문은 순위 경쟁형 레이스로 운영합니다. 각 경기의 순위는 결승선을 먼저 통과한 순서를 기준으로 결정합니다.': 'The Crew Invitational division will be conducted as a placement-based race. Rankings for each race will be determined by the order in which teams cross the finish line.',
    '순위 산정 원칙': 'Ranking Principles',
    '1위, 2위, 3위 등 경기 결과는 결승선 통과 순서로 판단합니다.': 'Results such as 1st, 2nd, and 3rd place are judged by finish-line order.',
    '공식 순위는 심판 판정과 결승선 통과 장면 확인을 기준으로 확정합니다.': 'Official rankings will be confirmed based on judges’ decisions and review of finish-line footage.',
    '동일 경기 안에서 먼저 들어온 크루가 상위 순위를 차지합니다.': 'Within the same race, the crew that finishes earlier ranks higher.',
    '결승선 통과 장면이 혼재되거나 육안 판정이 어려운 경우에는 기록 측정 배번을 통해 각 팀의 기록을 확인하여 최종 순위를 보조 판정합니다.': 'If the finish-line order is unclear or difficult to determine visually, timing bib data may be reviewed as a supplementary basis for final ranking.',
    '즉, 크루 초청 부문은 통과 순서가 우선 원칙이며, 기록 측정 배번 데이터는 판정 보조 수단으로 활용합니다.': 'For the Crew Invitational division, finish order remains the primary standard, while timing bib data serves as a supplementary judging tool.',
    '코스 구성': 'Course Structure',
    '본 대회 코스는 300m 길이의 8자 형태 코스로 운영합니다.': 'The race will take place on a 300m figure-eight course.',
    '참가자는 반드시 지정된 동선에 따라 주행해야 하며, 코스 이탈 또는 임의 단축은 허용되지 않습니다.': 'Participants must follow the designated route. Leaving the course or taking shortcuts is strictly prohibited.',
    '코스 주행 원칙': 'Course Running Principles',
    '참가자는 대회장 내 설치된 코스 안내 사인과 운영 스태프의 유도에 따라 주행합니다.': 'Participants must follow on-site course signage and staff guidance throughout the race.',
    '지정된 진행 방향을 역주행하거나, 코스를 임의로 벗어나거나, 일부 구간을 생략해서는 안 됩니다.': 'Participants must not run against the designated direction, leave the course, or skip any section.',
    '잘못된 코스로 진입한 경우에도 본인의 책임 원칙이 적용되며, 필요 시 기록 인정이 불가할 수 있습니다.': 'Participants are responsible for entering and following the correct course. Records may not be recognized if a participant enters the wrong course.',
    '안전 및 운영 통제': 'Safety and Operational Control',
    '코스 내에는 운영 스태프와 심판이 배치되며, 참가자는 현장 통제에 반드시 협조해야 합니다. 안전 또는 운영상 필요 시 일부 구간의 진행 방식은 현장에서 조정될 수 있습니다.': 'Event staff and judges will be stationed along the course. Participants must comply with on-site instructions, and certain sections may be adjusted on-site for safety or operational reasons.',
    '공식 인계 방식': 'Official Handoff Method',
    '본 대회는 기록 측정 배번을 통해 기록을 측정하므로, 릴레이 주자 간 인계는 반드시 정해진 인계 구간 내에서 진행해야 합니다.': 'Because records are measured through timing bibs, relay handoffs must take place within the designated handoff zone.',
    '바통 또는 어깨끈은 반드시 대회가 지정한 인계 구역 안에서 주고받아야 합니다.': 'The baton or shoulder strap must be exchanged inside the handoff zone designated by the event.',
    '인계 구역 밖에서 바통을 넘기거나, 바통 없이 다음 주자가 출발하는 것은 허용되지 않습니다.': 'Passing the baton outside the handoff zone or starting the next leg without the baton is not allowed.',
    '인계 방식은 손에서 손으로 직접 전달하는 것을 원칙으로 합니다.': 'The handoff should be made directly from hand to hand.',
    '인계 구간 위반': 'Handoff Zone Violations',
    '다음과 같은 경우 운영본부 및 심판진 판단에 따라 경고, 기록 불인정 또는 실격 처리할 수 있습니다.': 'The following violations may result in a warning, record invalidation, or disqualification at the discretion of event headquarters and judges.',
    '인계 구역 밖에서 바통 또는 어깨끈을 전달한 경우': 'Transferring the baton or shoulder strap outside the handoff zone',
    '앞 주자가 인계 전 코스를 이탈한 경우': 'The previous runner leaves the course before the handoff',
    '다음 주자가 바통 인계 전에 먼저 출발한 경우': 'The next runner starts before receiving the baton',
    '바통을 전달받지 않고 다음 주행을 시작한 경우': 'Starting the next leg without receiving the baton',
    '바통 분실': 'Lost Baton',
    '바통 또는 어깨끈을 떨어뜨린 경우, 해당 팀 선수가 직접 회수해야 합니다.': 'If the baton or shoulder strap is dropped, the team’s athlete must retrieve it directly.',
    '회수 과정에서 타 팀 주행을 방해해서는 안 됩니다.': 'Retrieval must not interfere with other teams’ running.',
    '고의적 방해 또는 위험한 동선이 발생할 경우 심판 판정에 따라 제재할 수 있습니다.': 'Intentional interference or dangerous movement may be penalized according to judges’ decisions.',
    '선수 대기 시간': 'Athlete Waiting Time',
    '모든 참가자는 본인 순서 10분 전까지 선수 대기 공간에 도착해 대기해야 합니다.': 'All participants must arrive at the athlete waiting area at least 10 minutes before their turn.',
    '일반 참가 부문, 크루 초청 부문 모두 동일하게 적용합니다.': 'This applies equally to both the general entry and crew invitational divisions.',
    '운영진은 대기 공간에서 참가자 신원을 확인한 후 출전 절차를 진행합니다.': 'Staff will verify participant identity in the waiting area before proceeding with race entry procedures.',
    '선수 확인 절차': 'Athlete Check Procedure',
    '신분증 지참 의무': 'ID Requirement',
    '참가자는 신분증을 반드시 지참해야 하며, 신분 확인이 불가능할 경우 출전이 제한될 수 있습니다. 인정 가능한 신분 확인 수단은 운영본부가 사전 공지한 기준에 따릅니다.': 'Participants must bring valid identification. If identity cannot be verified, participation may be restricted. Accepted forms of identification will follow the criteria announced in advance by event headquarters.',
    '지각 및 미대기 규정': 'Late Arrival and Waiting Rules',
    '참가자가 본인 출발 순서 기준 10분 전까지 선수 대기 공간에 도착하지 않은 경우, 출전 준비 미완료로 간주할 수 있습니다. 특히 경기 출발 후 선수 대기 공간에 도착한 경우에는 실격 처리합니다. 팀 릴레이 종목의 경우, 해당 주자의 미도착으로 정상 인계가 불가능하면 해당 팀은 기록 인정이 제한되거나 실격 처리될 수 있습니다.': 'If a participant does not arrive at the athlete waiting area at least 10 minutes before their start order, they may be considered unprepared for entry. Arrival after the race has started will result in disqualification. In team relay events, if a runner’s absence makes a normal handoff impossible, the team’s record may be invalidated or the team may be disqualified.',
    '출발 방식': 'Start Method',
    '모든 출발은 운영진 또는 스타터의 신호에 따라 진행합니다. 출발선 정렬 완료 후 스타트하며, 임의 출발은 허용되지 않습니다.': 'All starts proceed according to signals from staff or the starter. Races start after athletes are aligned at the start line, and arbitrary starts are not allowed.',
    '부정 출발 및 출발 방해': 'False Starts and Start Interference',
    '출발 신호 이전에 임의로 출발할 경우 경고 또는 재출발 조치가 가능하며, 반복 위반 또는 타 팀 방해가 발생할 경우 제재할 수 있습니다.': 'Starting before the start signal may result in a warning or restart. Repeated violations or interference with other teams may be penalized.',
    '추월 및 주행 질서': 'Passing and Running Conduct',
    '앞선 주자를 추월할 경우 상대 주자의 주행을 방해해서는 안 됩니다. 밀치기, 진로 방해, 고의적 접촉 등은 금지합니다.': 'When passing another runner, participants must not interfere with that runner’s movement. Pushing, blocking, and intentional contact are prohibited.',
    '공통 실격 사유': 'Common disqualification reasons',
    '기록 불인정 또는 판정 보류 가능 사유': 'Possible record invalidation or pending judgment reasons',
    '사유': 'Reason',
    '판정 권한': 'Judging Authority',
    '최종 순위와 실격 여부에 대한 판정 권한은 대회 심판진 및 운영본부에 있습니다. 공식 기록, 수기 기록, 현장 관찰, 영상 확인 등을 종합해 최종 판정합니다.': 'Final authority over rankings and disqualification rests with the event judges and headquarters. Final decisions will be made based on official records, manual records, on-site observations, and video review.',
    '이의 제기': 'Appeals',
    '순위 또는 판정에 대한 이의는 팀 대표자 또는 참가자 본인이 지정된 시간 내 운영본부에 제기할 수 있습니다. 단, 경기 종료 후 상당 시간이 경과한 이후에는 이의 제기가 제한될 수 있습니다. 최종 판정 결과는 운영본부 결정에 따릅니다.': 'Appeals regarding rankings or decisions may be submitted to event headquarters within the designated period by the team representative or the participant. Appeals may be restricted after a significant amount of time has passed following the race. Final decisions will be made by event headquarters.',
    '본인 확인': 'Identity verification',
    '신분증 확인': 'ID check',
    '배번 및 출전 순서 확인': 'Bib and race order check',
    '슈즈 및 착장 확인(필요 시)': 'Shoes and outfit check (if needed)',
    '출발 구역 안내': 'Start area guidance',
    '1. 신청 및 선발 관련': '1. Application and Selection',
    '2. 참가 확정 및 양도 제한': '2. Participation Confirmation and Transfer Restrictions',
    '3. 대회 운영 및 복장 규정': '3. Event Operations and Dress Code',
    '4. 건강 상태 자가 점검 및 책임': '4. Health Self-Assessment and Responsibility',
    '5. 우천 및 천재지변': '5. Rain and Force Majeure',
    '본 대회는 데상트 코리아(DK몰) 회원가입 및 로그인을 완료한 회원에 한해 신청이 가능하며, 비회원 신청은 불가합니다.': 'Applications are open only to members who have completed registration and login on Descente Korea (DK Mall). Non-member applications will not be accepted.',
    '신청 후 주자 변경 및 정보 수정은 원칙적으로 불가하오니 신중하게 작성해 주시기 바랍니다.': 'Runner changes and information edits are generally not permitted after submission. Please complete the application carefully.',
    '2인/4인 릴레이 팀 신청 시, 팀원 전원이 개별적으로 신청 및 접수를 완료해야 합니다.': 'For 2-person and 4-person relay team entries, all team members must complete individual application and registration.',
    '팀 매칭은 입력하신 [팀명]과 [대표자 연락처 뒷 4자리] 정보가 팀원 전원 일치할 경우에만 정상 처리됩니다. 정보 불일치로 인한 팀 매칭 실패 시 선발 대상에서 제외될 수 있습니다.': 'Team matching will be processed only when the team name and last four digits of the representative’s phone number match across all team members. If matching fails due to inconsistent information, the team may be excluded from selection.',
    '대한육상연맹, 트라이애슬론 등 전문 체육 선수로 등록되어있거나 현역 선수 및 등록 말소 후 2년이 지나지 않은 경우는 참가가 제한되며, 참가 시 시상 대상에서 제외됩니다.': 'Participation is restricted for registered or active professional athletes, including those registered with athletics or triathlon federations, as well as those whose registration was canceled less than 2 years ago. Such participants will be excluded from awards if they take part.',
    '참가자로 선정된 분들에게는 \'DK 온라인스토어\' 카카오톡 플러스 친구 메시지로 개별 안내 메시지가 발송되며, 이후 유선 연락(전화)을 통한 참가 여부 확인 절차를 거쳐야 참가가 최종 확정됩니다.': 'Selected participants will receive an individual notice via the DK Online Store KakaoTalk Plus Friend channel. Participation will be finalized only after a follow-up phone confirmation process.',
    '\'DK 온라인스토어\' 카카오톡 플러스 친구 채널을 차단하셨을 경우, 참가자 선정 안내 메시지를 전달받지 못할 수 있으니 유의해 주시기 바랍니다.': 'Please note that if the DK Online Store KakaoTalk Plus Friend channel is blocked, the selection notice may not be delivered.',
    '참가자 선정 안내 메시지가 발송된 후 지정된 기간 내에 개별적으로 유선 연락이 진행될 예정입니다. 해당 통화를 통해 참가 여부에 대한 의사를 밝혀주셔야만 참가가 최종 확정됩니다. 안내된 기간 내에 지속적으로 연락이 닿지 않을 경우 참가 의사가 없는 것으로 간주되어 예비 선정자에게 기회가 넘어가게 되오니 유의해 주시기 바랍니다.': 'After selection notices are sent, individual phone calls will be made within the designated period. Participation will be finalized only after the participant confirms their intent by phone. If the participant cannot be reached during the announced period, it may be deemed that they do not intend to participate, and the opportunity may be offered to an alternate participant.',
    '참가권의 타인 양도, 대리 신청, 판매는 엄격히 금지됩니다. 부정 참가 적발 시 기록 무효 처리 및 향후 데상트가 주최하는 모든 행사의 참여가 제한됩니다.': 'Transfer, proxy application, and sale of participation rights are strictly prohibited. If fraudulent participation is identified, records will be invalidated and participation in future Descente-hosted events may be restricted.',
    '참가비가 없는 무료 행사인 만큼, 확정 후 사전 연락 없이 불참(노쇼)하실 경우 향후 이벤트 참여에 불이익을 받을 수 있습니다.': 'As this is a free event, confirmed participants who do not attend without prior notice may be subject to restrictions on future event participation.',
    '모든 참가자는 대회 당일 본인 확인을 위해 실물 신분증(또는 공인 모바일 신분증)을 반드시 지참해야 합니다. 신분증 미지참 시 참가가 제한될 수 있습니다.': 'All participants must bring a physical ID or official mobile ID for identity verification on race day. Participation may be restricted without ID.',
    '레이스의 공정성을 위해 주최 측에서 제공하는 대회 기념 티셔츠와 현장에서 대여하는 \'델타프로 EXP V3\' 러닝화 착용은 필수입니다. 하의와 양말은 자율이며, 지정 복장 미착용 시 레이스 참여가 불가합니다.': 'To ensure fairness, all participants must wear the commemorative event T-shirt provided by the organizer and the DELTAPRO EXP V3 running shoes rented on-site. Bottoms and socks may be chosen freely. Participants not wearing the required items will not be allowed to race.',
    '현장 기록 측정은 넷타임(Net-time) 방식으로 운영되며, 오류 방지를 위해 현장 운영 인원이 초시계를 활용해 함께 기록을 측정합니다.': 'On-site timing will use the net-time method, and staff will also record times with stopwatches to help prevent timing errors.',
    '기록 측정용 칩은 번호표(배번호) 뒷면에 부착되어 있습니다. 칩을 떼어내거나 구부리는 등 훼손할 경우 기록 측정이 불가하며, 이에 따른 기록 누락은 주최 측에서 책임지지 않습니다.': 'The timing chip is attached to the back of the bib. If the chip is removed, bent, or damaged, timing may not be possible, and the organizer is not responsible for missing records caused by such damage.',
    '참가자는 반드시 본인의 건강 상태를 고려하여 신청해야 합니다. 주최 측은 행사 진행 중 발생하는 사고에 대비해 보험에 가입하나, 본인의 지병이나 무리한 레이스, 부주의로 발생한 부상 및 사고에 대해서는 책임을 지지 않습니다.': 'Participants must apply only after considering their own health condition. The organizer carries insurance for accidents during the event but is not responsible for injuries or accidents caused by pre-existing conditions, excessive racing, or negligence.',
    '대회 전 의료기관의 검진을 통해 무리가 없는지 스스로 확인하시길 권장하며, 레이스 도중 신체에 이상이 느껴질 경우 즉시 레이스를 중단하고 주변 안전 요원이나 응급 의료진에게 도움을 요청하시기 바랍니다.': 'Participants are encouraged to check their condition with a medical institution before the race. If you feel any physical abnormality during the race, stop immediately and ask nearby safety staff or medical personnel for help.',
    '일반적인 우천 시에도 대회는 정상 진행됩니다. 단, 태풍, 폭우 등 참가가 불가능한 천재지변 발생 시 주최 측의 판단 하에 대회가 연기 또는 취소될 수 있으며, 관련 내용은 사전에 개별 안내됩니다.': 'The event will proceed in normal rain. However, in the event of severe weather or force majeure, such as typhoons or heavy rain, that makes participation impossible, the organizer may postpone or cancel the event and will notify participants in advance.',
    '2026 데상트 어웨이큰 에키덴 레이스 규정': '2026 Descente Awaken Ekiden Race Rules',
    '2026 데상트 어웨이큰 에키덴 레이스 대회 개요': '2026 Descente Awaken Ekiden Race Overview',
    '2026 데상트 어웨이큰 에키덴 레이스 대회 코스 안내': '2026 Descente Awaken Ekiden Race Course Guide',
    '2026 데상트 어웨이큰 에키덴 레이스 운영 시간표': '2026 Descente Awaken Ekiden Race Schedule',
    '2026 데상트 어웨이큰 에키덴 레이스 운영 안내': '2026 Descente Awaken Ekiden Race Operations Guide',
    '2026 데상트 어웨이큰 에키덴 레이스 유의 사항': '2026 Descente Awaken Ekiden Race Important Notes',
    '2026 데상트 어웨이큰 에키덴 레이스 참가 안내': '2026 Descente Awaken Ekiden Race Entry Guide',
    '2026년 6월 22일(월) ~ 23일(화)': 'June 22 (Mon) - 23 (Tue), 2026',
    '2026년 4월 24일(금) ~ 5월 5일(화)': 'April 24 (Fri) - May 5 (Tue), 2026',
    '6월 22일(월) | 일반 참가 부문': 'June 22 (Mon) | General Entry Division',
    '기념 반팔 티셔츠, 러닝 양말, 기록 측정용 배번호': 'Commemorative short-sleeve T-shirt, running socks, and timing bib',
    '대회 기념 긴팔 티셔츠, 크루 싱글렛, 하프 타이츠, 러닝 양말, 델타프로 EXP V3, 기록 측정용 배번호': 'Commemorative long-sleeve T-shirt, crew singlet, half tights, running socks, DELTAPRO EXP V3, and timing bib',
    '대회 패키지로 제공되는 대회 기념 반팔 티셔츠, 러닝 양말': 'Commemorative short-sleeve T-shirt and running socks provided in the race package',
    '주최측이 제공하는 러닝 양말': 'Running socks provided by the organizer',
    '하의는 자유롭게 착용 가능': 'Bottoms may be worn freely',
    '브랜드 초청 크루': 'Brand-invited crews',
    '대회 소개 영상': 'Intro video',
    '데상트 러닝 커뮤니티 DRC 안내': 'Descente Running Community DRC Guide',
    '레이스 규정 바로가기': 'Go to race rules',
    '메뉴 열기': 'Open menu',
    '언어 선택': 'Language selection',
    '호스트': 'Host',
    '꼬뮨드서울': 'Commune D Seoul',
    '낙원': 'Nakwon',
    '노룰즈러닝': 'No Rules Running',
    '러쉬': 'Rush',
    '서울비너스': 'Seoul Venus',
    '와우산 30': 'Wausan 30',
    '와우산30': 'Wausan30',
    '정직': 'Honest',
    '미래농원': 'Mirae Farm',
    '상암월드컵경기장': 'Sangam World Cup Stadium',
    '크라이치즈버거 상암점': 'Cry Cheeseburger Sangam Branch',
    '남자 3인 릴레이': 'Men’s 3-person Relay',
    '남자 개인전': 'Men’s Individual',
    '여자 3인 릴레이': 'Women’s 3-person Relay',
    '여자 개인전': 'Women’s Individual',
    '경기 중 계측 장비 오류가 발생한 경우': 'In cases where timing equipment errors occur during the race',
    '기록 측정 배번 미부착 또는 훼손': 'Failure to wear the timing bib or damage to it',
    '배번 식별이 불가한 상태로 경기한 경우': 'Racing in a state where the bib could not be identified',
    '신분 확인이 불가능하거나 대리 참가가 확인된 경우': 'If identity verification is impossible or proxy participation is confirmed',
    '심판 및 운영진의 정당한 지시에 불응한 경우': 'Failure to comply with legitimate instructions from referees and event staff',
    '위험한 행위 또는 비신사적 행위를 한 경우': 'If dangerous or unsportsmanlike conduct occurs',
    '지정된 코스를 이탈하거나 일부 구간을 생략한 경우': 'If the designated course is left or part of the route is skipped',
    '타 참가자의 경기 진행을 방해한 경우': 'If another participant’s race progress is obstructed',
    '출발 후 선수 대기 공간에 도착한 경우': 'If arriving at the athlete waiting area after the start',
    '운영상 판독이 필요한 상황이 발생한 경우': 'If a situation requiring operational review occurs',
    '다음 각 호에 해당하는 경우 심판 및 운영본부 판단에 따라 실격 또는 기록 불인정 처리할 수 있습니다.': 'In any of the following cases, the referees and event headquarters may determine disqualification or non-recognition of the record.',
    '참가자로 선정된 분들에게는 \'DK 온라인스토어\' 카카오톡 플러스 친구 메시지로 개별 안내 메시지가 발송되며, 이후 유선 연락(전화)을 통한 참가 여부 확인 절차를 거쳐야 참가가 최종 확정됩니다.': 'Selected participants will receive an individual notice via the DK Online Store KakaoTalk Plus Friend message, and participation will be finalized only after a follow-up phone confirmation process.',
    '참가자로 선정된 분들에게는 \'DK 온라인스토어\' 카카오톡 플러스 친구 메시지로 개별 안내 메시지가 발송되며, 이후 유선 연락(전화)을 통한 참가 여부 확인 절차를 거쳐야 참가가 최종 확정됩니다.': 'Selected participants will receive an individual notice via the DK Online Store KakaoTalk Plus Friend message, and participation will be finalized only after a follow-up phone confirmation process.',
    '레이스를 통해 확보한 JTBC 서울마라톤 티켓은 참가자 동의하에 크루 내에서 자유롭게 사용할 수 있습니다.': 'JTBC Seoul Marathon tickets secured through the race may be freely used within the crew with the participant’s consent.',
    '레이스의 공정성을 위해 주최 측에서 제공하는 대회 기념 티셔츠와 현장에서 대여하는 \'델타프로 EXP V3\' 러닝화 착용은 필수입니다. 하의와 양말은 자율이며, 지정 복장 미착용 시 레이스 참여가 불가합니다.': 'To ensure race fairness, wearing the commemorative event T-shirt provided by the organizer and the DELTAPRO EXP V3 running shoes rented on-site is mandatory. Bottoms and socks are optional, and participants not wearing the designated gear may not take part in the race.',
    '레이스의 공정성을 위해 주최 측에서 제공하는 대회 기념 티셔츠와 현장에서 대여하는 \'델타프로 EXP V3\' 러닝화 착용은 필수입니다. 하의와 양말은 자율이며, 지정 복장 미착용 시 레이스 참여가 불가합니다.': 'To ensure race fairness, wearing the commemorative event T-shirt provided by the organizer and the DELTAPRO EXP V3 running shoes rented on-site is mandatory. Bottoms and socks are optional, and participants not wearing the designated gear may not take part in the race.',
    '\'DK 온라인스토어\' 카카오톡 플러스 친구 채널을 차단하셨을 경우, 참가자 선정 안내 메시지를 전달받지 못할 수 있으니 유의해 주시기 바랍니다.': 'Please note that if you block the DK Online Store KakaoTalk Plus Friend channel, you may not receive the participant selection notice.',
    '\'DK 온라인스토어\' 카카오톡 플러스 친구 채널을 차단하셨을 경우, 참가자 선정 안내 메시지를 전달받지 못할 수 있으니 유의해 주시기 바랍니다.': 'Please note that if you block the DK Online Store KakaoTalk Plus Friend channel, you may not receive the participant selection notice.',
    '10만 원 상당의 데상트 제품': 'DESCENTE products worth KRW 100,000',
    '2026 JTBC 서울마라톤 티켓 + 델타프로 EXP V3 + 10만 원 상당의 데상트 제품': '2026 JTBC Seoul Marathon ticket + DELTAPRO EXP V3 + DESCENTE products worth KRW 100,000',
    '4위~10위 팀': '4th-10th place teams',
    '1회차': 'Session 1',
    '2회차': 'Session 2',
    '3회차': 'Session 3',
    '4회차': 'Session 4',
    '5회차': 'Session 5',
    '6회차': 'Session 6',
    '7회차': 'Session 7',
    '8회차': 'Session 8',
    '9회차': 'Session 9',
    '10회차': 'Session 10',
    '5/18(월)': '5/18 (Mon)',
    '5/21(목)': '5/21 (Thu)',
    '5/29(금)': '5/29 (Fri)',
    '6/6(토)': '6/6 (Sat)',
    '6/9(화)': '6/9 (Tue)',
    '6/16(화)': '6/16 (Tue)',
    '6/19(금)': '6/19 (Fri)',
    '6/20(토)': '6/20 (Sat)',
    "'DK 온라인스토어' 카카오톡 플러스 친구 채널을 차단하셨을 경우, 참가자 선정 안내 메시지를 전달받지 못할 수 있으니 유의해 주시기 바랍니다.": 'Please note that if you block the DK Online Store KakaoTalk Plus Friend channel, you may not receive the participant selection notice.',
    "레이스의 공정성을 위해 주최 측에서 제공하는 대회 기념 티셔츠와 현장에서 대여하는 '델타프로 EXP V3' 러닝화 착용은 필수입니다. 하의와 양말은 자율이며, 지정 복장 미착용 시 레이스 참여가 불가합니다.": 'To ensure race fairness, wearing the commemorative event T-shirt provided by the organizer and the DELTAPRO EXP V3 running shoes rented on-site is mandatory. Bottoms and socks are optional, and participants not wearing the designated gear may not take part in the race.',
    "참가자로 선정된 분들에게는 'DK 온라인스토어' 카카오톡 플러스 친구 메시지로 개별 안내 메시지가 발송되며, 이후 유선 연락(전화)을 통한 참가 여부 확인 절차를 거쳐야 참가가 최종 확정됩니다.": 'Selected participants will receive an individual notice via the DK Online Store KakaoTalk Plus Friend message, and participation will be finalized only after a follow-up phone confirmation process.',
    '어웨이큰 에키덴 레이스는 참가자 모두가 동일한 조건에서 레이스를 경험하고 경쟁할 수 있도록 운영하는 것을 기본 원칙으로 합니다. 따라서 부문별로 주최측이 지정한 의류와 신발을 반드시 착용해야 하며, 이를 통해 경기의 공정성과 대회 콘셉트의 일관성을 함께 확보하고자 합니다.': 'The Awaken Ekiden Race is operated on the core principle that all participants should experience and compete under the same conditions. Accordingly, participants must wear the clothing and shoes designated by the organizer for each division in order to ensure both competitive fairness and consistency with the event concept.',
    '즉, 이번 대회는 단순한 자유 복장 러닝 이벤트가 아니라, 동일한 퍼포먼스 환경 안에서 레이스를 진행하는 것이 핵심 규정입니다.': 'In other words, this event is not simply a free-dress running event. A core rule is that the race is conducted within the same performance environment for everyone.'
  },
  ja: {
    '2026 데상트 어웨이큰 에키덴 레이스': '2026 デサント アウェイクン駅伝レース',
    '2026 데상트 어웨이큰 에키덴 레이스 참가자 안내 홈페이지': '2026 デサント アウェイクン駅伝レース 参加者向け案内サイト',
    '2026 데상트 어웨이큰 에키덴 레이스 참고용 페이지(비공식)': '2026 デサント アウェイクン駅伝レース 参考ページ（非公式）',
    '데상트 에키덴 레이스': 'デサント駅伝レース',
    '데상트 러닝 커뮤니티': 'デサント ランニング コミュニティ',
    '참가 안내': 'エントリー案内',
    '레이스 운영': 'レース運営案内',
    '대회 코스': '大会コース',
    '규정': 'レース規定',
    '시간표': 'スケジュール',
    '유의 사항': '注意事項',
    '맨 위로': 'ページ上部へ',
    '데상트 어웨이큰 에키덴 레이스는 에키덴에서 영감을 받은 팀 릴레이 레이스입니다. 개인의 기록보다 함께 달리는 가치에 집중하며, 러너 간의 팀워크와 열정을 극대화하는 데 초점을 맞췄습니다.': 'デサント アウェイクン駅伝レースは、駅伝の精神から着想を得たチームリレーイベントです。個人記録だけでなく、共に走る価値に焦点を当て、ランナー同士のチームワーク、熱量、つながりを引き出します。',
    '한 사람의 움직임이 다음 주자에게 이어지고, 각자의 힘이 하나의 흐름으로 완성되는 순간. 이 레이스는 함께 달리고, 연결됨을 느끼며, 한계를 넘어 깨어나는 경험을 만들어갑니다.': '一人の走りが次のランナーへ受け継がれ、それぞれの力が一つの流れになる瞬間。このレースは、共に走り、つながりを感じ、自分の限界を超えて目覚める体験を届けます。',
    '대회명': '大会名',
    '개최일': '開催日',
    '장소': '会場',
    '주최/주관': '主催／主管',
    '전쟁기념관 지하 주차장': '戦争記念館 地下駐車場',
    '데상트(DESCENTE)': 'デサント（DESCENTE）',
    'Race Information': '大会情報',
    '대회 안내': '大会案内',
    '대회 기본 정보': '大会概要',
    'Race Entry': 'エントリー',
    '참가 부문 안내': '参加部門案内',
    '운영일': '実施日',
    '일반 참가 부문': '一般参加部門',
    '크루 초청 부문': 'クルー招待部門',
    '2026년 6월 22일(월)': '2026年6月22日（月）',
    '2026년 6월 23일(화)': '2026年6月23日（火）',
    '참가 규모': '参加規模',
    '최대 162명, 총 9개 크루': '最大162名、全9クルー',
    '레이스 구성': 'レース構成',
    '남자 2인 릴레이, 여자 2인 릴레이, 혼성 4인 릴레이': '男子2人リレー、女子2人リレー、混合4人リレー',
    '개인전, 3인 릴레이, 혼성 4인 릴레이, 혼성 6인 릴레이': '個人戦、3人リレー、混合4人リレー、混合6人リレー',
    '진행 방식': '実施方式',
    '기록 순위로 순위를 산정하는 타임트라이얼 방식': '公式記録に基づき順位を算定するタイムトライアル方式',
    '예선과 결선으로 운영되는 순위 경쟁 방식': '予選・決勝で実施する順位競争方式',
    '각 부문 기록 순위에 따라 팀 전원에게 리워드 지급': '各部門の公式記録順位に応じて、対象チーム全員にアワードを授与',
    '부문별 우승팀 및 종합 포인트 상위 크루 대상 리워드 지급': '部門別優勝チームおよび総合ポイント上位クルーにアワードを授与',
    '대회 접수 안내 보기': 'エントリー案内を見る',
    '레이스 운영 보기': 'レース運営案内を見る',
    '대회 접수 안내': '大会エントリー案内',
    '6월 22일(월) | 일반 참가 접수 부문': '6月22日（月）｜一般参加部門',
    '6월 23일(화) | 크루 초청 부문': '6月23日（火）｜クルー招待部門',
    '신청 기간': '申込期間',
    '참가 인원': '参加人数',
    '참가 대상': '参加対象',
    '진행 시간': '実施時間',
    '참가 방식': 'エントリー方法',
    '선정 발표': '選定発表',
    '참가 패키지': '参加パッケージ',
    '2026년 5월 11일(월) ~ 5월 25일(월)': '2026年5月11日（月）〜5月25日（月）',
    '240명': '240名',
    '만 19세 이상 일반 러너': '満19歳以上の一般ランナー',
    '6월 22일(월) 오후 7시 50분 ~ 오후 10시 (체크인: 오후 7시)': '6月22日（月）19:50〜22:00（チェックイン：19:00）',
    '신청 기간 내 참가 신청을 접수한 뒤, 운영 기준에 따라 참가팀을 선정합니다.': '申込期間終了後、運営基準に基づき参加チームを選定いたします。',
    '2026년 6월 5일(금) 오후 6시, 선정자 대상 문자 안내': '2026年6月5日（金）18:00に、選定者へSMSにてご案内いたします。',
    '기념 반팔 티셔츠, 기록 측정용 배번호': '記念半袖Tシャツ、計測用ナンバーカード',
    '신청 정보 입력 항목': '申込情報入力項目',
    '신청 방법': '申込方法',
    '데상트 공식 홈페이지 접속': 'DESCENTE公式ホームページへアクセス',
    '레이스 페이지 확인': 'レースページを確認',
    '팀 단위 신청': 'チーム単位で申込',
    '팀원 전원 개별 신청 완료': 'チームメンバー全員が個別申込完了',
    '참가자 발표 확인': '参加者発表を確認',
    '어웨이큰 에키덴 레이스 및 데상트 러닝 커뮤니티 페이지 확인': 'アウェイケン駅伝レースおよびデサント ランニング コミュニティページを確認',
    '참여를 희망하는 DRC 프로그램 신청': '参加を希望するDRCプログラムに申込',
    '신청 완료': '申込完了',
    '최종 참가자 발표 확인': '最終参加者発表を確認',
    '데상트 공식 홈페이지 접속 → 어웨이큰 에키덴 레이스 및 데상트 러닝 커뮤니티 페이지 확인 → 참여를 희망하는 DRC 프로그램 신청 → 신청 완료 → 최종 참가자 발표 확인': 'DESCENTE公式ホームページへアクセス -> アウェイケン駅伝レースおよびデサント ランニング コミュニティページを確認 -> 参加を希望するDRCプログラムに申込 -> 申込完了 -> 最終参加者発表を確認',
    'DRC는 크루원과 게스트 모두 데상트 공식 홈페이지를 통해 직접 신청해야 하며, 신청 완료 후 최종 참가자 발표를 통해 참가 여부가 확정됩니다.': 'DRCはクルー員とゲストのいずれもDESCENTE公式ホームページを通じて直接申込する必要があり、申込完了後に最終参加者発表を通じて参加可否が確定します。',
    '데상트 공식 홈페이지 접속 → 레이스 페이지 확인 → 팀 단위 신청 → 팀원 전원 개별 신청 완료 → 참가자 발표 확인': 'DESCENTE公式ホームページへアクセス -> レースページを確認 -> チーム単位で申込 -> チームメンバー全員が個別申込完了 -> 参加者発表を確認',
    '일반 참가 부문은 데상트 공식 홈페이지 내 어웨이큰 에키덴 레이스 페이지를 통해 신청할 수 있습니다. 참가를 원하는 팀은 신청 페이지에서 참가 부문을 확인한 뒤 팀 단위로 신청을 진행해야 하며, 팀 구성원 전원이 각각 신청을 완료해야 정상 접수로 인정됩니다. 신청 완료 후에는 참가자 발표 일정에 맞춰 최종 선정 여부를 확인할 수 있습니다.': '一般参加部門は、DESCENTE公式ホームページ内のアウェイケン駅伝レースページから申込できます。参加を希望するチームは、申込ページで参加部門を確認したうえでチーム単位で申込を進める必要があり、チーム構成員全員がそれぞれ申込を完了して初めて正式受付となります。申込完了後は、参加者発表日程に合わせて最終選定結果をご確認いただけます。',
    '크루별 별도 안내': 'クルーごとの別途案内',
    '참가 부문 확인': '参加部門を確認',
    '별도 신청폼 작성': '別途申込フォームに入力',
    '운영 안내 확인': '運営案内を確認',
    '크루별 별도 안내 → 참가 부문 확인 → 별도 신청폼 작성 → 신청 완료 → 운영 안내 확인': 'クルーごとの別途案内 -> 参加部門を確認 -> 別途申込フォームに入力 -> 申込完了 -> 運営案内を確認',
    '크루 초청 부문은 사전 초청된 크루를 대상으로 별도 안내할 예정입니다. 각 크루는 전달받은 안내에 따라 참가 가능 부문과 인원을 확인한 뒤, 별도 신청폼을 통해 참가 신청을 진행합니다. 신청 완료 후에는 대회 운영과 관련한 세부 사항을 별도로 안내받게 됩니다.': 'クルー招待部門は、事前に招待されたクルーを対象に別途ご案内する予定です。各クルーは受け取った案内に従って参加可能部門と人数を確認したうえで、別途申込フォームを通じて参加申込を進めます。申込完了後は、大会運営に関する詳細事項を別途ご案内いたします。',
    '입력 항목': '入力項目',
    '내용': '内容',
    '대표자 이름': '代表者名',
    '팀 대표자 성명': 'チーム代表者氏名',
    '휴대폰 번호 뒷자리': '携帯電話番号下4桁',
    '본인 확인 및 참가자 식별용': '本人確認および参加者識別用',
    '팀명': 'チーム名',
    '참가 팀명': '参加チーム名',
    '나에게 러닝이란?': '私にとってランニングとは？',
    '신청자 스토리 및 선발 참고 문항': '申込者ストーリーおよび選考参考項目',
    '2026년 4월 24일(금) ~ 5월 3일(일)': '2026年4月24日（金）〜5月3日（日）',
    '최대 162명': '最大162名',
    '초청 크루': '招待クルー',
    '6월 23일(화) 오후 7시 50분 ~ 오후 10시 (체크인: 오후 7시)': '6月23日（火）19:50〜22:00（チェックイン：19:00）',
    '브랜드 초청 크루 총 9개 팀 운영': 'ブランド招待による全9クルーで実施いたします。',
    '해당 없음': '該当なし',
    '대회 기념 긴팔 티셔츠, 크루 싱글렛, 하프 타이츠, 델타프로 EXP V3, 기록 측정용 배번호': '大会記念長袖Tシャツ、クルーシングレット、ハーフタイツ、DELTAPRO EXP V3、計測用ナンバーカード',
    '참가 신청': '参加申込',
    '일반 참가 부문': '一般参加部門',
    '크루 초청 부문': 'クルー招待部門',
    '일반 참가 부문 | 2026년 6월 22일(월)': '一般参加部門｜2026年6月22日（月）',
    '크루 초청 부문 | 2026년 6월 23일(화)': 'クルー招待部門｜2026年6月23日（火）',
    '레이스 부문': 'レース部門',
    '부문': '部門',
    '모집 규모': '募集規模',
    '남자 2인 릴레이': '男子2人リレー',
    '여자 2인 릴레이': '女子2人リレー',
    '혼성 4인 릴레이': '混合4人リレー',
    '남자부 개인전': '男子個人戦',
    '여자부 개인전': '女子個人戦',
    '남자부 3인 릴레이': '男子3人リレー',
    '여자부 3인 릴레이': '女子3人リレー',
    '혼성 6인 릴레이': '混合6人リレー',
    '개인전': '個人戦',
    '3인 릴레이': '3人リレー',
    '혼성 릴레이': '混合リレー',
    '구분': '区分',
    '40팀': '40チーム',
    '20팀': '20チーム',
    '레이스 방식': 'レース方式',
    '일반 참가 부문은 타임트라이얼 방식으로 진행됩니다.': '一般参加部門はタイムトライアル方式で実施いたします。',
    '각 팀은 기록 측정용 배번호를 통해 기록이 측정됩니다.': '各チームの公式記録は、計測用ナンバーカードにより測定されます。',
    '순위는 각 레이스 부문별 기록 순위에 따라 결정됩니다.': '順位は各レース部門における公式記録に基づいて決定いたします。',
    '복장 규정': '服装規定',
    '어웨이큰 에키덴 레이스는 참가자 모두가 동일한 조건에서 레이스를 경험하고 경쟁할 수 있도록 운영하는 것을 기본 원칙으로 한다. 따라서 부문별로 주최측이 지정한 의류와 신발을 반드시 착용해야 하며, 이를 통해 경기의 공정성과 대회 콘셉트의 일관성을 함께 확보하고자 한다.': 'アウェイケン駅伝レースは、参加者全員が同一条件でレースを経験し競技できるよう運営することを基本原則としています。そのため、部門ごとに主催者が指定したウェアとシューズを必ず着用していただき、競技の公正性と大会コンセプトの一貫性をともに確保します。',
    '즉, 이번 대회는 단순한 자유 복장 러닝 이벤트가 아니라, 동일한 퍼포먼ス 환경 안에서 레이스를 진행하는 것이 핵심 규정이다.': 'つまり、本大会は単なる自由な服装のランニングイベントではなく、同一のパフォーマンス環境の中でレースを実施することが中核規定です。',
    '의무 착용 항목': '着用必須項目',
    '대회 패키지로 제공되는 대회 기념 반팔 티셔츠': '大会パッケージに含まれる大会記念半袖Tシャツ',
    '주최측이 제공하는 트라이얼용 델타프로 EXP V3': '主催者が提供するトライアル用 DELTAPRO EXP V3',
    '자유 착용 가능 항목': '自由着用可能項目',
    '하의, 양말은 자유롭게 착용 가능': 'ボトムス、ソックスは自由に着用可能です',
    '부문별 리워드': '部門別アワード',
    '남자/여자부 개인전': '男子/女子個人戦',
    '남자/여자부 3인 릴레이': '男子/女子3人リレー',
    '순위': '順位',
    '1위': '1位',
    '2026 JTBC 서울마라톤 티켓': '2026 JTBCソウルマラソンチケット',
    '2026 JTBC 서울마라톤 티켓 전원 지급': '2026 JTBCソウルマラソンチケットをチーム全員に授与',
    '기록 순위': '記録順位',
    '리워드': 'アワード',
    '1위~3위 팀': '1〜3位チーム',
    '4위~6위 팀': '4〜6位チーム',
    '7위~10위 팀': '7〜10位チーム',
    '1위~5위 팀': '1〜5位チーム',
    '6위~10위 팀': '6〜10位チーム',
    '11위~15위 팀': '11〜15位チーム',
    '남자/여자 2인 릴레이': '男子/女子2人リレー',
    '혼성 4인 릴레이': '混合4人リレー',
    '2026 JTBC 서울마라톤 티켓 + 델타프로 EXP V3': '2026 JTBCソウルマラソンチケット + DELTAPRO EXP V3',
    '2026 JTBC 서울마라톤 티켓 + 델타프로 ADV V2': '2026 JTBCソウルマラソンチケット + DELTAPRO ADV V2',
    '델타프로 ADV V2': 'DELTAPRO ADV V2',
    '각 레이스 부문에서 기록 순위에 따라 리워드가 제공되며, 해당 순위 팀 전원에게 지급됩니다.': '各レース部門の公式記録順位に応じてアワードを提供し、対象順位のチームメンバー全員に授与いたします。',
    '안내 사항': 'ご案内事項',
    '참가자 편의를 위해 대회장 내에 산업용 이동식 에어컨을 설치할 예정입니다.': '参加者の利便性向上のため、会場内に産業用移動式エアコンを設置する予定です。',
    '일반 참가 부문과 크루 초청 부문 간 중복 참가는 불가합니다.': '一般参加部門とクルー招待部門の重複参加はできません。',
    '레이스 부문별 토너먼트 조 추첨은 5월 9일(토, 예정) 온라인 또는 오프라인으로 진행할 예정입니다.': 'レース部門別のトーナメント組み合わせ抽選は、5月9日（土、予定）にオンラインまたはオフラインで実施する予定です。',
    '대회 규정은 조 추첨 당일 운영진 회의를 통해 상세히 안내할 예정이며, 필요 시 대회 전까지 일부 내용을 수정·보완할 수 있습니다.': '大会規定は抽選当日の運営会議を通じて詳細にご案内する予定であり、必要に応じて大会前までに一部内容を修正・補完する場合があります。',
    '일반 참가 부문 리워드로 제공되는 JTBC 서울마라톤 티켓은 타인에게 양도할 수 없습니다.': '一般参加部門のリワードとして提供されるJTBCソウルマラソンチケットは、他人へ譲渡できません。',
    '순위는 남자 2인 릴레이 / 여자 2인 릴레이 / 혼성 4인 릴레이 각 부문별로 별도 산정됩니다.': '順位は男子2人リレー、女子2人リレー、混合4人リレーの各部門ごとに別途算定します。',
    '기록 측정용 배번호는 대회 당일 반드시 지정된 방식으로 착용해야 합니다.': '計測用ナンバーカードは大会当日に必ず指定された方法で着用してください。',
    '혼성 4인 릴레이 구성은 남자 2인 + 여자 2인입니다.': '混合4人リレーは男子2名＋女子2名で構成します。',
    '혼성 릴레이 구성': '混合リレー構成',
    '남자 2인 + 여자 2인': '男子2名＋女子2名',
    '남자 3인 + 여자 3인': '男子3名＋女子3名',
    '크루 초청 부문은 예선 - 결선 방식으로 진행됩니다.': 'クルー招待部門は、予選・決勝方式で実施いたします。',
    '총 9개 크루가 참가하며, 3개 크루씩 1개 조로 예선을 진행합니다.': '全9クルーが参加し、予選は3クルーずつ1組として実施いたします。',
    '각 부문은 총 3개 조로 운영되며, 각 조 1위 팀만 결선에 진출합니다.': '各部門は全3組で運営され、各組1位のチームのみ決勝へ進出します。',
    '따라서 모든 부문은 결선 3팀 동일 구조로 운영됩니다.': 'そのため、すべての部門は決勝3チームの同一形式で実施されます。',
    '토너먼트 대진표': 'トーナメント対戦表',
    '예선': '予選',
    '3개 크루 참가': '3クルーが参加',
    '1위 팀 결선 진출': '1位チームが決勝進出',
    '결선': '決勝',
    '결선 3팀': '決勝3チーム',
    '1조 1위': '1組1位',
    '2조 1위': '2組1位',
    '3조 1위': '3組1位',
    '최종 순위 결정': '最終順位決定',
    '주최측이 제공하는 크루 싱글렛': '主催者が提供するクルーシングレット',
    '주최측이 제공하는 하프 타이즈': '主催者が提供するハーフタイツ',
    '주최측이 제공하는 델타프로 EXP V3': '主催者が提供する DELTAPRO EXP V3',
    '양말은 자유롭게 착용 가능': 'ソックスは自由に着用可能です',
    '크루 초청 부문 종합 포인트 운영안': 'クルー招待部門 総合ポイント運営案',
    '결선 순위': '決勝順位',
    '부여 포인트': '付与ポイント',
    '1위': '1位',
    '2위': '2位',
    '3위': '3位',
    '10 포인트': '10ポイント',
    '6 포인트': '6ポイント',
    '3 포인트': '3ポイント',
    '각 레이스 부문 결선 결과 기준으로 1~3위 크루에 포인트를 부여합니다.': '各レース部門の決勝結果に基づき、1〜3位のクルーにポイントを付与します。',
    '포인트 집계 대상 부문': 'ポイント集計対象部門',
    '대상 부문': '対象部門',
    '총 6개 부문 점수를 합산해 종합 순위를 산정합니다.': '全6部門の点数を合算して総合順位を算定します。',
    '최종 리워드': '総合アワード',
    '종합 우승 크루': '総合優勝クルー',
    '종합 준우승 크루': '総合準優勝クルー',
    'JTBC 서울마라톤 티켓 8장': 'JTBCソウルマラソンチケット8枚',
    'JTBC 서울마라톤 티켓 5장': 'JTBCソウルマラソンチケット5枚',
    '동점 처리 기준': '同点処理基準',
    '포인트 합산 결과가 같을 경우 아래 기준 순으로 최종 순위를 결정합니다.': 'ポイント合計が同点の場合、以下の基準に従って最終順位を決定いたします。',
    '부문별 1위 횟수가 많은 크루 우선': '部門別1位の回数が多いクルーを優先',
    '혼성 6인 릴레이 순위가 높은 크루 우선': '混合6人リレーの順位が高いクルーを優先',
    '즉, 종합 포인트가 같더라도 더 많은 부문에서 우승한 크루가 우선이며, 1위 횟수까지 같을 경우에는 마지막 메인 종목인 혼성 6인 릴레이 성적이 높은 크루가 최종 상위 순위를 차지합니다.': 'つまり、総合ポイントが同じでも、より多くの部門で優勝したクルーが優先されます。1位回数も同じ場合は、最後のメイン種目である混合6人リレーの成績が高いクルーが上位となります。',
    '출전 유의사항': '出場に関する注意事項',
    '남자부/여자부 개인전과 남자부/여자부 3인 릴레이는 같은 참가자가 중복 출전할 수 없습니다.': '男子／女子個人戦と男子／女子3人リレーは、同じ参加者が重複出場することはできません。',
    '혼성 릴레이는 개인전 또는 3인 릴레이 출전자가 추가로 1개 부문까지 중복 출전할 수 있습니다.': '混合リレーは、個人戦または3人リレー出場者が追加で1部門まで重複出場できます。',
    '단, 1인이 3개 이상 부문에 출전하는 것은 불가합니다.': 'ただし、1人が3部門以上に出場することはできません。',
    '운영 시간표': '大会スケジュール',
    'Day 1 | 일반 참가': 'Day 1｜一般参加',
    'Day 2 | 크루 초청': 'Day 2｜クルー招待',
    '시간': '時間',
    '비고': '備考',
    '체크인': 'チェックイン',
    '배번 수령, 신분 확인, 선수 대기 안내': 'ナンバーカード受取、本人確認、選手待機案内',
    '오프닝 및 경기 브리핑': 'オープニングおよび競技ブリーフィング',
    '경기 방식, 코스, 인계 구역, 리워드 안내': '競技方式、コース、引継ぎ区域、リワード案内',
    '크루 소개, 경기 방식, 포인트 규정 안내': 'クルー紹介、競技方式、ポイント規定案内',
    '10회차 / 4팀 동시 출발': '10回／4チーム同時スタート',
    '5회차 / 4팀 동시 출발': '5回／4チーム同時スタート',
    '시상식': '表彰式',
    '1~15위 팀 시상 및 촬영': '1〜15位チーム表彰および撮影',
    '부문 시상 + 종합 시상': '部門表彰＋総合表彰',
    '개인전 및 3인 릴레이 예선': '個人戦および3人リレー予選',
    '개인전 및 3인 릴레이 결선': '個人戦および3人リレー決勝',
    '혼성 릴레이 예선': '混合リレー予選',
    '혼성 릴레이 결선': '混合リレー決勝',
    '3개 조 운영': '3組で運営',
    '조별 1위 진출': '各組1位が進出',
    '혼성 4인 / 혼성 6인': '混合4人／混合6人',
    '회차': '回',
    '조': '組',
    '운영 정보': '運営詳細',
    '1회차당 4팀 출발': '1回につき4チーム出発',
    '남자 2인 릴레이 상세 시간표': '男子2人リレー詳細時間表',
    '여자 2인 릴레이 상세 시간표': '女子2人リレー詳細時間表',
    '혼성 4인 릴레이 상세 시간표': '混合4人リレー詳細時間表',
    '남자 개인전 예선 상세 시간표': '男子個人戦予選詳細時間表',
    '여자 개인전 예선 상세 시간표': '女子個人戦予選詳細時間表',
    '남자 3인 릴레이 예선 상세 시간표': '男子3人リレー予選詳細時間表',
    '여자 3인 릴레이 예선 상세 시간표': '女子3人リレー予選詳細時間表',
    '개인전 및 3인 릴레이 결선 상세 시간표': '個人戦および3人リレー決勝詳細時間表',
    '혼성 4인 릴레이 예선 상세 시간표': '混合4人リレー予選詳細時間表',
    '혼성 6인 릴레이 예선 상세 시간표': '混合6人リレー予選詳細時間表',
    '혼성 릴레이 결선 상세 시간표': '混合リレー決勝詳細時間表',
    '예선 1조': '予選1組',
    '예선 2조': '予選2組',
    '예선 3조': '予選3組',
    '결선': '決勝',
    '남자 개인전 예선': '男子個人戦予選',
    '여자 개인전 예선': '女子個人戦予選',
    '남자 3인 릴레이 예선': '男子3人リレー予選',
    '여자 3인 릴레이 예선': '女子3人リレー予選',
    '혼성 4인 릴레이 예선': '混合4人リレー予選',
    '혼성 6인 릴레이 예선': '混合6人リレー予選',
    '남자 개인전 결선': '男子個人戦決勝',
    '여자 개인전 결선': '女子個人戦決勝',
    '남자 3인 릴레이 결선': '男子3人リレー決勝',
    '여자 3인 릴레이 결선': '女子3人リレー決勝',
    '혼성 4인 릴레이 결선': '混合4人リレー決勝',
    '혼성 6인 릴레이 결선': '混合6人リレー決勝',
    '대회 개요': '大会概要',
    '참가비': '参加費',
    '무료': '無料',
    '300m 길이의 8자 형태 코스로 운영': '300mの8の字型コースで運営',
    '코스 이미지는 추후 업데이트 예정': 'コースマップは後日更新予定です。',
    '데상트 러닝 커뮤니티 (DRC)': 'デサント ランニング コミュニティ（DRC）',
    '데상트 러닝 커뮤니티(DRC)는 함께 달리고, 경험을 나누며, 러닝을 일상으로 만드는 커뮤니티입니다. 대회 전 약 8주간 크루별 호스트 프로그램과 일반 러너 참여 방식으로 운영됩니다.': 'デサント ランニング コミュニティ（DRC）は、共に走り、経験を共有し、ランニングを日常に広げていくランニングコミュニティです。大会までの約8週間、各クルーによるホストプログラムおよび一般ランナー向け参加プログラムとして運営いたします。',
    '운영 기간': '運営期間',
    '운영 횟수': '運営回数',
    '공통 제공': '共通提供',
    '5월 3주차 ~ 6월 3주차': '5月第3週〜6月第3週',
    '총 8회': '全8回',
    '슈즈 트라이얼, F&B, 짐보관': 'シューズトライアル、F&B、荷物預かり',
    '프로그램명': 'プログラム名',
    '진행일': '実施日',
    '집결지': '集合場所',
    '특징': '特徴',
    '업데이트 예정': '更新予定',
    '시티 트레일 러닝': 'シティトレイルランニング',
    '시티런 & 커피런': 'シティラン＆コーヒーラン',
    '반포종합운동장 7K 인터벌': '盤浦総合運動場 7Kインターバル',
    '커피런 + 이벤트': 'コーヒーラン＋イベント',
    '그룹 릴레이 레이스': 'グループリレーレース',
    '버거런': 'バーガーラン',
    '빙고런': 'ビンゴラン',
    '시티 & 한강 러닝': 'シティ＆漢江ランニング',
    '레이스 규정': 'レース規定',
    '운영 원칙': '運営原則',
    '경기 방식': '競技方式',
    '코스 규정': 'コース規定',
    '인계 규정': '引継ぎ規定',
    '선수 확인': '選手確認',
    '출발/진행': 'スタート／進行',
    '실격 사유': '失格事由',
    '판정/이의': '判定／異議',
    '1. 운영 기본 원칙': '1. 運営基本原則',
    '2. 경기 방식 및 순위 산정': '2. 競技方式および順位算定',
    '3. 대회 코스 규정': '3. 大会コース規定',
    '4. 바통(어깨끈 포함) 인계 규정': '4. バトン（肩ひも含む）引継ぎ規定',
    '5. 선수 확인 및 대기 규정': '5. 選手確認および待機規定',
    '6. 출발 및 진행 규정': '6. スタートおよび進行規定',
    '7. 실격 및 기록 불인정 사유': '7. 失格および記録不認定事由',
    '8. 판정 및 이의 제기': '8. 判定および異議申立て',
    '본 대회는 일반 참가 부문과 크루 초청 부문으로 나누어 운영하며, 각 부문별 경기 방식과 순위 산정 기준은 아래와 같습니다.': '本大会は一般参加部門とクルー招待部門に分けて運営いたします。各部門の競技方式および順位算定基準は以下のとおりです。',
    '기록 측정 배번 기준으로 기록을 산정하여 순위를 결정': '計測用ナンバーカードで測定した記録に基づき順位を決定',
    '결승선 통과 순서 기준으로 순위를 결정': 'フィニッシュライン通過順に基づき順位を決定',
    '모든 참가자는 대회 운영진 및 심판의 안내에 따라 경기해야 하며, 정해진 코스와 규정을 준수하지 않을 경우 기록 인정이 제한되거나 실격 처리될 수 있습니다.': 'すべての参加者は、大会運営スタッフおよび審判の案内に従って競技してください。指定コースおよび規定を遵守しない場合、記録が認定されない、または失格となる場合があります。',
    '기록 측정 원칙': '記録測定原則',
    '일반 참가 부문은 기록 경쟁형 릴레이 레이스로 운영합니다. 각 팀의 최종 순위는 기록 측정 배번을 통해 측정된 공식 기록을 기준으로 산정합니다.': '一般参加部門は、記録競争型のリレーレースとして実施いたします。各チームの最終順位は、計測用ナンバーカードで測定された公式記録に基づき算定します。',
    '공식 기록은 기록 측정 배번을 통해 자동 집계된 기록을 기준으로 합니다.': '公式記録は計測用ナンバーカードにより自動集計された記録を基準とします。',
    '각 팀의 최종 순위는 해당 부문의 전체 참가팀 기록을 일괄 비교하여 결정합니다.': '各チームの最終順位は、該当部門の全参加チームの記録を一括比較して決定します。',
    '경기 중 같은 레이스에 여러 팀이 동시에 출발하더라도, 최종 순위는 결승선 통과 순서가 아니라 공식 기록 기준으로 결정합니다.': '競技中に同じレースで複数チームが同時に出発しても、最終順位はフィニッシュライン通過順ではなく公式記録を基準に決定します。',
    '예외 상황': '例外状況',
    '기록 측정 배번에 오류가 발생하거나 계측 데이터 확인이 어려운 경우를 대비해, 대회장 내 심판은 육상대회용 초시계(스톱워치)로 별도 기록을 측정하고 수기로 기록합니다.': '計測用ナンバーカードにエラーが発生した場合や計測データの確認が困難な場合に備え、会場内の審判は陸上競技用ストップウォッチで別途記録を測定し、手書きで記録します。',
    '수기 기록은 기본적으로 참고 기록으로 사용합니다.': '手書き記録は基本的に参考記録として使用します。',
    '다만 기록 측정 배번 오류 등 공식 계측이 불가능한 경우에는 운영본부 및 심판진 확인을 거쳐 수기 기록을 보조 기준으로 활용할 수 있습니다.': 'ただし、計測用ナンバーカードのエラーなどにより公式計測が不可能な場合は、運営本部および審判団の確認を経て手書き記録を補助基準として活用できます。',
    '크루 초청 부문은 순위 경쟁형 레이스로 운영합니다. 각 경기의 순위는 결승선을 먼저 통과한 순서를 기준으로 결정합니다.': 'クルー招待部門は、順位競争型レースとして実施いたします。各競技の順位は、フィニッシュラインの通過順に基づき決定します。',
    '순위 산정 원칙': '順位算定原則',
    '1위, 2위, 3위 등 경기 결과는 결승선 통과 순서로 판단합니다.': '1位、2位、3位などの競技結果はフィニッシュライン通過順で判断します。',
    '공식 순위는 심판 판정과 결승선 통과 장면 확인을 기준으로 확정합니다.': '公式順位は審判判定とフィニッシュライン通過場面の確認を基準に確定します。',
    '동일 경기 안에서 먼저 들어온 크루가 상위 순위를 차지합니다.': '同一競技内で先に入ったクルーが上位順位となります。',
    '결승선 통과 장면이 혼재되거나 육안 판정이 어려운 경우에는 기록 측정 배번을 통해 각 팀의 기록을 확인하여 최종 순위를 보조 판정합니다.': 'フィニッシュライン通過時の状況が混在し、目視での判定が困難な場合は、計測用ナンバーカードの記録を確認し、最終順位の補助判定に活用します。',
    '즉, 크루 초청 부문은 통과 순서가 우선 원칙이며, 기록 측정 배번 데이터는 판정 보조 수단으로 활용합니다.': 'クルー招待部門では、通過順を優先基準とし、計測用ナンバーカードのデータは判定補助として使用します。',
    '코스 구성': 'コース構成',
    '본 대회 코스는 300m 길이의 8자 형태 코스로 운영합니다.': '本大会のコースは300mの8の字型コースで運営します。',
    '참가자는 반드시 지정된 동선에 따라 주행해야 하며, 코스 이탈 또는 임의 단축은 허용되지 않습니다.': '参加者は必ず指定された動線に従って走行してください。コース離脱または任意の短縮は認められません。',
    '코스 주행 원칙': 'コース走行原則',
    '참가자는 대회장 내 설치된 코스 안내 사인과 운영 스태프의 유도에 따라 주행합니다.': '参加者は会場内に設置されたコース案内サインと運営スタッフの誘導に従って走行します。',
    '지정된 진행 방향을 역주행하거나, 코스를 임의로 벗어나거나, 일부 구간을 생략해서는 안 됩니다.': '指定された進行方向に逆走したり、コースを任意に外れたり、一部区間を省略してはいけません。',
    '잘못된 코스로 진입한 경우에도 본인의 책임 원칙이 적용되며, 필요 시 기록 인정이 불가할 수 있습니다.': '誤ったコースに入った場合も本人責任の原則が適用され、必要に応じて記録が認定されないことがあります。',
    '안전 및 운영 통제': '安全および運営統制',
    '코스 내에는 운영 스태프와 심판이 배치되며, 참가자는 현장 통제에 반드시 협조해야 합니다. 안전 또는 운영상 필요 시 일부 구간의 진행 방식은 현장에서 조정될 수 있습니다.': 'コース内には運営スタッフおよび審判を配置します。参加者は現場での案内・統制に必ずご協力ください。安全または運営上必要な場合、一部区間の進行方式を現場で調整することがあります。',
    '공식 인계 방식': '公式引継ぎ方式',
    '본 대회는 기록 측정 배번을 통해 기록을 측정하므로, 릴레이 주자 간 인계는 반드시 정해진 인계 구간 내에서 진행해야 합니다.': '本大会は計測用ナンバーカードで記録を測定するため、リレー走者間の引継ぎは必ず定められた引継ぎ区間内で行う必要があります。',
    '바통 또는 어깨끈은 반드시 대회가 지정한 인계 구역 안에서 주고받아야 합니다.': 'バトンまたは肩ひもは必ず大会が指定した引継ぎ区域内で受け渡ししてください。',
    '인계 구역 밖에서 바통을 넘기거나, 바통 없이 다음 주자가 출발하는 것은 허용되지 않습니다.': '引継ぎ区域外でバトンを渡したり、バトンなしで次の走者が出発することは認められません。',
    '인계 방식은 손에서 손으로 직접 전달하는 것을 원칙으로 합니다.': '引継ぎ方式は手から手へ直接渡すことを原則とします。',
    '인계 구간 위반': '引継ぎ区間違反',
    '다음과 같은 경우 운영본부 및 심판진 판단에 따라 경고, 기록 불인정 또는 실격 처리할 수 있습니다.': '以下に該当する場合、運営本部および審判団の判断により、警告、記録不認定、または失格となることがあります。',
    '인계 구역 밖에서 바통 또는 어깨끈을 전달한 경우': '引継ぎ区域外でバトンまたは肩ひもを渡した場合',
    '앞 주자가 인계 전 코스를 이탈한 경우': '前走者が引継ぎ前にコースを離脱した場合',
    '다음 주자가 바통 인계 전에 먼저 출발한 경우': '次走者がバトン引継ぎ前に先に出発した場合',
    '바통을 전달받지 않고 다음 주행을 시작한 경우': 'バトンを受け取らずに次の走行を開始した場合',
    '바통 분실': 'バトン紛失',
    '바통 또는 어깨끈을 떨어뜨린 경우, 해당 팀 선수가 직접 회수해야 합니다.': 'バトンまたは肩ひもを落とした場合、該当チームの選手が直接回収しなければなりません。',
    '회수 과정에서 타 팀 주행을 방해해서는 안 됩니다.': '回収過程で他チームの走行を妨害してはいけません。',
    '고의적 방해 또는 위험한 동선이 발생할 경우 심판 판정에 따라 제재할 수 있습니다.': '故意の妨害または危険な動線が発生した場合、審判判定により制裁されることがあります。',
    '선수 대기 시간': '選手待機時間',
    '모든 참가자는 본인 순서 10분 전까지 선수 대기 공간에 도착해 대기해야 합니다.': 'すべての参加者は自身の順番の10分前までに選手待機エリアに到着して待機しなければなりません。',
    '일반 참가 부문, 크루 초청 부문 모두 동일하게 적용합니다.': '一般参加部門、クルー招待部門の双方に同様に適用します。',
    '운영진은 대기 공간에서 참가자 신원을 확인한 후 출전 절차를 진행합니다.': '運営スタッフは待機エリアで参加者の身元を確認した後、出場手続きを進行します。',
    '선수 확인 절차': '選手確認手順',
    '신분증 지참 의무': '身分証持参義務',
    '참가자는 신분증을 반드시 지참해야 하며, 신분 확인이 불가능할 경우 출전이 제한될 수 있습니다. 인정 가능한 신분 확인 수단은 운영본부가 사전 공지한 기준에 따릅니다.': '参加者は有効な身分証を必ずご持参ください。本人確認ができない場合、出場が制限されることがあります。認められる本人確認手段は、運営本部が事前に告知する基準に従います。',
    '지각 및 미대기 규정': '遅刻および未待機規定',
    '참가자가 본인 출발 순서 기준 10분 전까지 선수 대기 공간에 도착하지 않은 경우, 출전 준비 미완료로 간주할 수 있습니다. 특히 경기 출발 후 선수 대기 공간에 도착한 경우에는 실격 처리합니다. 팀 릴레이 종목의 경우, 해당 주자의 미도착으로 정상 인계가 불가능하면 해당 팀은 기록 인정이 제한되거나 실격 처리될 수 있습니다.': '参加者が自身の出発順の10分前までに選手待機エリアへ到着しない場合、出場準備未完了とみなされることがあります。特に競技開始後に待機エリアへ到着した場合は失格となります。チームリレー種目では、該当走者の未到着により正常な引継ぎが不可能な場合、そのチームは記録認定が制限されたり失格となることがあります。',
    '출발 방식': 'スタート方式',
    '모든 출발은 운영진 또는 스타터의 신호에 따라 진행합니다. 출발선 정렬 완료 후 스타트하며, 임의 출발은 허용되지 않습니다.': 'すべてのスタートは運営スタッフまたはスターターの合図に従って行います。スタートライン整列完了後にスタートし、任意のスタートは認められません。',
    '부정 출발 및 출발 방해': '不正スタートおよびスタート妨害',
    '출발 신호 이전에 임의로 출발할 경우 경고 또는 재출발 조치가 가능하며, 반복 위반 또는 타 팀 방해가 발생할 경우 제재할 수 있습니다.': 'スタート合図前に任意に出発した場合、警告または再スタート措置が可能であり、反復違反または他チーム妨害が発生した場合は制裁されることがあります。',
    '추월 및 주행 질서': '追い越しおよび走行秩序',
    '앞선 주자를 추월할 경우 상대 주자의 주행을 방해해서는 안 됩니다. 밀치기, 진로 방해, 고의적 접촉 등은 금지합니다.': '前方の走者を追い越す場合、相手走者の走行を妨げてはいけません。押す行為、進路妨害、故意の接触などは禁止します。',
    '공통 실격 사유': '共通失格事由',
    '기록 불인정 또는 판정 보류 가능 사유': '記録不認定または判定保留の可能性がある事由',
    '사유': '事由',
    '판정 권한': '判定権限',
    '최종 순위와 실격 여부에 대한 판정 권한은 대회 심판진 및 운영본부에 있습니다. 공식 기록, 수기 기록, 현장 관찰, 영상 확인 등을 종합해 최종 판정합니다.': '最終順位および失格可否に関する判定権限は、大会審判団および運営本部にあります。公式記録、手書き記録、現場確認、映像確認などを総合して最終判定を行います。',
    '이의 제기': '異議申立て',
    '순위 또는 판정에 대한 이의는 팀 대표자 또는 참가자 본인이 지정된 시간 내 운영본부에 제기할 수 있습니다. 단, 경기 종료 후 상당 시간이 경과한 이후에는 이의 제기가 제한될 수 있습니다. 최종 판정 결과는 운영본부 결정에 따릅니다.': '順位または判定に関する異議は、チーム代表者または参加者本人が、指定時間内に運営本部へ申し立てることができます。ただし、競技終了から一定時間が経過した後は、異議申立てを受け付けられない場合があります。最終判定は運営本部の決定に従います。',
    '본인 확인': '本人確認',
    '신분증 확인': '身分証確認',
    '배번 및 출전 순서 확인': 'ナンバーカードおよび出場順確認',
    '슈즈 및 착장 확인(필요 시)': 'シューズおよび着用確認（必要時）',
    '출발 구역 안내': 'スタートエリア案内',
    '1. 신청 및 선발 관련': '1. 申込および選抜関連',
    '2. 참가 확정 및 양도 제한': '2. 参加確定および譲渡制限',
    '3. 대회 운영 및 복장 규정': '3. 大会運営および服装規定',
    '4. 건강 상태 자가 점검 및 책임': '4. 健康状態の自己確認および責任',
    '5. 우천 및 천재지변': '5. 雨天および自然災害',
    '본 대회는 데상트 코리아(DK몰) 회원가입 및 로그인을 완료한 회원에 한해 신청이 가능하며, 비회원 신청은 불가합니다.': '本大会へのお申し込みは、デサントコリア（DKモール）への会員登録およびログインを完了した会員に限ります。非会員のお申し込みはできません。',
    '신청 후 주자 변경 및 정보 수정은 원칙적으로 불가하오니 신중하게 작성해 주시기 바랍니다.': 'お申し込み後の走者変更および情報修正は、原則としてできません。内容を十分にご確認のうえ、ご入力ください。',
    '2인/4인 릴레이 팀 신청 시, 팀원 전원이 개별적으로 신청 및 접수를 완료해야 합니다.': '2人／4人リレーチームでお申し込みの場合、チームメンバー全員が個別に申込・受付を完了する必要があります。',
    '팀 매칭은 입력하신 [팀명]과 [대표자 연락처 뒷 4자리] 정보가 팀원 전원 일치할 경우에만 정상 처리됩니다. 정보 불일치로 인한 팀 매칭 실패 시 선발 대상에서 제외될 수 있습니다.': 'チームマッチングは、入力された［チーム名］および［代表者連絡先下4桁］がチームメンバー全員で一致した場合のみ正常に処理されます。情報不一致によりマッチングできない場合、選抜対象から除外されることがあります。',
    '대한육상연맹, 트라이애슬론 등 전문 체육 선수로 등록되어있거나 현역 선수 및 등록 말소 후 2년이 지나지 않은 경우는 참가가 제한되며, 참가 시 시상 대상에서 제외됩니다.': '大韓陸上連盟、トライアスロン等の専門競技選手として登録されている方、現役選手、または登録抹消後2年が経過していない方は参加が制限されます。参加された場合も表彰対象外となります。',
    '참가자로 선정된 분들에게는 \'DK 온라인스토어\' 카카오톡 플러스 친구 메시지로 개별 안내 메시지가 발송되며, 이후 유선 연락(전화)을 통한 참가 여부 확인 절차를 거쳐야 참가가 최종 확정됩니다.': '参加者として選定された方には、「DKオンラインストア」KakaoTalk Plus Friendメッセージにて個別にご案内いたします。その後、電話による参加意思確認を経て、参加が最終確定となります。',
    '\'DK 온라인스토어\' 카카오톡 플러스 친구 채널을 차단하셨을 경우, 참가자 선정 안내 메시지를 전달받지 못할 수 있으니 유의해 주시기 바랍니다.': '「DKオンラインストア」KakaoTalk Plus Friendチャンネルをブロックしている場合、選定案内メッセージを受信できない場合がありますのでご注意ください。',
    '참가자 선정 안내 메시지가 발송된 후 지정된 기간 내에 개별적으로 유선 연락이 진행될 예정입니다. 해당 통화를 통해 참가 여부에 대한 의사를 밝혀주셔야만 참가가 최종 확정됩니다. 안내된 기간 내에 지속적으로 연락이 닿지 않을 경우 참가 의사가 없는 것으로 간주되어 예비 선정자에게 기회가 넘어가게 되오니 유의해 주시기 바랍니다.': '参加者選定案内メッセージの送信後、指定期間内に個別に電話連絡を行います。電話にて参加意思を確認できた場合に限り、参加が最終確定となります。案内期間内に継続して連絡が取れない場合、参加意思がないものとみなし、補欠選定者へ参加機会が移る場合があります。',
    '참가권의 타인 양도, 대리 신청, 판매는 엄격히 금지됩니다. 부정 참가 적발 시 기록 무효 처리 및 향후 데상트가 주최하는 모든 행사의 참여가 제한됩니다.': '参加権の譲渡、代理申込、販売は固く禁止されています。不正参加が確認された場合、記録は無効となり、今後デサントが主催するすべてのイベントへの参加が制限されます。',
    '참가비가 없는 무료 행사인 만큼, 확정 후 사전 연락 없이 불참(노쇼)하실 경우 향후 이벤트 참여에 불이익을 받을 수 있습니다.': '参加費のない無料イベントのため、確定後に事前連絡なく不参加（ノーショー）となった場合、今後のイベント参加に不利益が生じることがあります。',
    '모든 참가자는 대회 당일 본인 확인을 위해 실물 신분증(또는 공인 모바일 신분증)을 반드시 지참해야 합니다. 신분증 미지참 시 참가가 제한될 수 있습니다.': 'すべての参加者は大会当日、本人確認のため実物の身分証（または公認モバイル身分証）を必ず持参してください。身分証未持参の場合、参加が制限されることがあります。',
    '레이스의 공정성을 위해 주최 측에서 제공하는 대회 기념 티셔츠와 현장에서 대여하는 \'델타프로 EXP V3\' 러닝화 착용은 필수입니다. 하의와 양말은 자율이며, 지정 복장 미착용 시 레이스 참여가 불가합니다.': 'レースの公平性確保のため、主催者が提供する大会記念Tシャツおよび現地で貸与する「DELTAPRO EXP V3」ランニングシューズの着用が必須です。ボトムスおよびソックスは自由ですが、指定アイテムを着用していない場合はレースに参加できません。',
    '현장 기록 측정은 넷타임(Net-time) 방식으로 운영되며, 오류 방지를 위해 현장 운영 인원이 초시계를 활용해 함께 기록을 측정합니다.': '現地記録測定はネットタイム方式で運営され、誤差防止のため運営スタッフがストップウォッチでも記録を測定します。',
    '기록 측정용 칩은 번호표(배번호) 뒷면에 부착되어 있습니다. 칩을 떼어내거나 구부리는 등 훼손할 경우 기록 측정이 불가하며, 이에 따른 기록 누락은 주최 측에서 책임지지 않습니다.': '計測用チップはナンバーカードの裏面に付いています。チップを外したり曲げたりして破損した場合、記録測定ができず、それによる記録漏れについて主催者は責任を負いません。',
    '참가자는 반드시 본인의 건강 상태를 고려하여 신청해야 합니다. 주최 측은 행사 진행 중 발생하는 사고에 대비해 보험에 가입하나, 본인의 지병이나 무리한 레이스, 부주의로 발생한 부상 및 사고에 대해서는 책임을 지지 않습니다.': '参加者は必ず自身の健康状態を考慮して申込む必要があります。主催者はイベント中の事故に備えて保険に加入しますが、本人の持病、無理なレース、不注意による負傷や事故については責任を負いません。',
    '대회 전 의료기관의 검진을 통해 무리가 없는지 스스로 확인하시길 권장하며, 레이스 도중 신체에 이상이 느껴질 경우 즉시 레이스를 중단하고 주변 안전 요원이나 응급 의료진에게 도움을 요청하시기 바랍니다.': '大会前に医療機関で検診を受け、無理がないかご自身で確認することを推奨します。レース中に身体の異常を感じた場合は直ちにレースを中断し、周囲の安全スタッフまたは救急医療スタッフに助けを求めてください。',
    '일반적인 우천 시에도 대회는 정상 진행됩니다. 단, 태풍, 폭우 등 참가가 불가능한 천재지변 발생 시 주최 측의 판단 하에 대회가 연기 또는 취소될 수 있으며, 관련 내용은 사전에 개별 안내됩니다.': '通常の雨天時も大会は予定どおり実施いたします。ただし、台風・豪雨など参加が困難な荒天または不可抗力が発生した場合、主催者の判断により大会を延期または中止する場合があります。該当内容は事前に個別にご案内いたします。',
    '2026 데상트 어웨이큰 에키덴 레이스 규정': '2026 デサント アウェイクン駅伝レース 規定',
    '2026 데상트 어웨이큰 에키덴 레이스 대회 개요': '2026 デサント アウェイクン駅伝レース 大会概要',
    '2026 데상트 어웨이큰 에키덴 레이스 대회 코스 안내': '2026 デサント アウェイクン駅伝レース コース案内',
    '2026 데상트 어웨이큰 에키덴 레이스 운영 시간표': '2026 デサント アウェイクン駅伝レース 運営時間表',
    '2026 데상트 어웨이큰 에키덴 레이스 운영 안내': '2026 デサント アウェイクン駅伝レース 運営案内',
    '2026 데상트 어웨이큰 에키덴 레이스 유의 사항': '2026 デサント アウェイクン駅伝レース 注意事項',
    '2026 데상트 어웨이큰 에키덴 레이스 참가 안내': '2026 デサント アウェイクン駅伝レース 参加案内',
    '2026년 6월 22일(월) ~ 23일(화)': '2026年6月22日（月）〜23日（火）',
    '2026년 4월 24일(금) ~ 5월 5일(화)': '2026年4月24日（金）〜5月5日（火）',
    '6월 22일(월) | 일반 참가 부문': '6月22日（月）｜一般参加部門',
    '기념 반팔 티셔츠, 러닝 양말, 기록 측정용 배번호': '記念半袖Tシャツ、ランニングソックス、計測用ナンバーカード',
    '대회 기념 긴팔 티셔츠, 크루 싱글렛, 하프 타이츠, 러닝 양말, 델타프로 EXP V3, 기록 측정용 배번호': '大会記念長袖Tシャツ、クルーシングレット、ハーフタイツ、ランニングソックス、DELTAPRO EXP V3、計測用ナンバーカード',
    '대회 패키지로 제공되는 대회 기념 반팔 티셔츠, 러닝 양말': '大会パッケージに含まれる大会記念半袖Tシャツ、ランニングソックス',
    '주최측이 제공하는 러닝 양말': '主催者が提供するランニングソックス',
    '하의는 자유롭게 착용 가능': 'ボトムスは自由に着用可能です',
    '브랜드 초청 크루': 'ブランド招待クルー',
    '대회 소개 영상': '大会紹介映像',
    '데상트 러닝 커뮤니티 DRC 안내': 'デサント ランニング コミュニティ DRC 案内',
    '레이스 규정 바로가기': 'レース規定を見る',
    '메뉴 열기': 'メニューを開く',
    '언어 선택': '言語選択',
    '호스트': 'ホスト',
    '꼬뮨드서울': 'コミューンドソウル',
    '낙원': 'ナグォン',
    '노룰즈러닝': 'ノールールズランニング',
    '러쉬': 'ラッシュ',
    '서울비너스': 'ソウルヴィーナス',
    '와우산 30': 'ワウサン 30',
    '와우산30': 'ワウサン30',
    '정직': 'ジョンジク',
    '미래농원': '未来農園',
    '상암월드컵경기장': '上岩ワールドカップ競技場',
    '크라이치즈버거 상암점': 'クライチーズバーガー上岩店',
    '남자 3인 릴레이': '男子3人リレー',
    '남자 개인전': '男子個人戦',
    '여자 3인 릴레이': '女子3人リレー',
    '여자 개인전': '女子個人戦',
    '경기 중 계측 장비 오류가 발생한 경우': '競技中に計測機器エラーが発生した場合',
    '기록 측정 배번 미부착 또는 훼손': '計測用ナンバーカードの未装着または破損',
    '배번 식별이 불가한 상태로 경기한 경우': 'ナンバーカードが識別できない状態で競技した場合',
    '신분 확인이 불가능하거나 대리 참가가 확인된 경우': '本人確認ができない、または代理参加が確認された場合',
    '심판 및 운영진의 정당한 지시에 불응한 경우': '審判および運営スタッフの正当な指示に従わなかった場合',
    '위험한 행위 또는 비신사적 행위를 한 경우': '危険行為またはスポーツマンシップに反する行為をした場合',
    '지정된 코스를 이탈하거나 일부 구간을 생략한 경우': '指定コースを逸脱したり、一部区間を省略した場合',
    '타 참가자의 경기 진행을 방해한 경우': '他の参加者の競技進行を妨げた場合',
    '출발 후 선수 대기 공간에 도착한 경우': 'スタート後に選手待機エリアへ到着した場合',
    '운영상 판독이 필요한 상황이 발생한 경우': '運営上、判定確認が必要な状況が発生した場合',
    '다음 각 호에 해당하는 경우 심판 및 운영본부 판단에 따라 실격 또는 기록 불인정 처리할 수 있습니다.': '次の各号に該当する場合、審判および運営本部の判断により失格または記録不認定となることがあります。',
    '참가자로 선정된 분들에게는 \'DK 온라인스토어\' 카카오톡 플러스 친구 메시지로 개별 안내 메시지가 발송되며, 이후 유선 연락(전화)을 통한 참가 여부 확인 절차를 거쳐야 참가가 최종 확정됩니다.': '参加者として選定された方には「DKオンラインストア」KakaoTalk Plus Friendメッセージで個別案内が送信され、その後の電話連絡による参加意思確認を経て参加が最終確定します。',
    '참가자로 선정된 분들에게는 \'DK 온라인스토어\' 카카오톡 플러스 친구 메시지로 개별 안내 메시지가 발송되며, 이후 유선 연락(전화)을 통한 참가 여부 확인 절차를 거쳐야 참가가 최종 확정됩니다.': '参加者として選定された方には「DKオンラインストア」KakaoTalk Plus Friendメッセージで個別案内が送信され、その後の電話連絡による参加意思確認を経て参加が最終確定します。',
    '레이스를 통해 확보한 JTBC 서울마라톤 티켓은 참가자 동의하에 크루 내에서 자유롭게 사용할 수 있습니다.': 'レースを通じて確保したJTBCソウルマラソンチケットは、参加者の同意のもとクルー内で自由に使用できます。',
    '레이스의 공정성을 위해 주최 측에서 제공하는 대회 기념 티셔츠와 현장에서 대여하는 \'델타프로 EXP V3\' 러닝화 착용은 필수입니다. 하의와 양말은 자율이며, 지정 복장 미착용 시 레이스 참여가 불가합니다.': 'レースの公平性を保つため、主催者が提供する大会記念Tシャツと現地貸出の「DELTAPRO EXP V3」ランニングシューズの着用は必須です。ボトムスとソックスは自由ですが、指定ウェア未着用の場合はレースに参加できません。',
    '레이스의 공정성을 위해 주최 측에서 제공하는 대회 기념 티셔츠와 현장에서 대여하는 \'델타프로 EXP V3\' 러닝화 착용은 필수입니다. 하의와 양말은 자율이며, 지정 복장 미착용 시 레이스 참여가 불가합니다.': 'レースの公平性を保つため、主催者が提供する大会記念Tシャツと現地貸出の「DELTAPRO EXP V3」ランニングシューズの着用は必須です。ボトムスとソックスは自由ですが、指定ウェア未着用の場合はレースに参加できません。',
    '\'DK 온라인스토어\' 카카오톡 플러스 친구 채널을 차단하셨을 경우, 참가자 선정 안내 메시지를 전달받지 못할 수 있으니 유의해 주시기 바랍니다.': '「DKオンラインストア」KakaoTalk Plus Friendチャンネルをブロックしている場合、参加者選定案内メッセージを受信できないことがありますのでご注意ください。',
    '\'DK 온라인스토어\' 카카오톡 플러스 친구 채널을 차단하셨을 경우, 참가자 선정 안내 메시지를 전달받지 못할 수 있으니 유의해 주시기 바랍니다.': '「DKオンラインストア」KakaoTalk Plus Friendチャンネルをブロックしている場合、参加者選定案内メッセージを受信できないことがありますのでご注意ください。',
    '10만 원 상당의 데상트 제품': '10万ウォン相当のDESCENTE製品',
    '2026 JTBC 서울마라톤 티켓 + 델타프로 EXP V3 + 10만 원 상당의 데상트 제품': '2026 JTBCソウルマラソンチケット + DELTAPRO EXP V3 + 10万ウォン相当のDESCENTE製品',
    '4위~10위 팀': '4〜10位チーム',
    '1회차': '1回目',
    '2회차': '2回目',
    '3회차': '3回目',
    '4회차': '4回目',
    '5회차': '5回目',
    '6회차': '6回目',
    '7회차': '7回目',
    '8회차': '8回目',
    '9회차': '9回目',
    '10회차': '10回目',
    '5/18(월)': '5/18（月）',
    '5/21(목)': '5/21（木）',
    '5/29(금)': '5/29（金）',
    '6/6(토)': '6/6（土）',
    '6/9(화)': '6/9（火）',
    '6/16(화)': '6/16（火）',
    '6/19(금)': '6/19（金）',
    '6/20(토)': '6/20（土）',
    "'DK 온라인스토어' 카카오톡 플러스 친구 채널을 차단하셨을 경우, 참가자 선정 안내 메시지를 전달받지 못할 수 있으니 유의해 주시기 바랍니다.": '「DKオンラインストア」KakaoTalk Plus Friendチャンネルをブロックしている場合、参加者選定案内メッセージを受信できないことがありますのでご注意ください。',
    "레이스의 공정성을 위해 주최 측에서 제공하는 대회 기념 티셔츠와 현장에서 대여하는 '델타프로 EXP V3' 러닝화 착용은 필수입니다. 하의와 양말은 자율이며, 지정 복장 미착용 시 레이스 참여가 불가합니다.": 'レースの公平性を保つため、主催者が提供する大会記念Tシャツと現地貸出の「DELTAPRO EXP V3」ランニングシューズの着用は必須です。ボトムスとソックスは自由ですが、指定ウェア未着用の場合はレースに参加できません。',
    "참가자로 선정된 분들에게는 'DK 온라인스토어' 카카오톡 플러스 친구 메시지로 개별 안내 메시지가 발송되며, 이후 유선 연락(전화)을 통한 참가 여부 확인 절차를 거쳐야 참가가 최종 확정됩니다.": '参加者として選定された方には「DKオンラインストア」KakaoTalk Plus Friendメッセージで個別案内が送信され、その後の電話連絡による参加意思確認を経て参加が最終確定します。',
    '어웨이큰 에키덴 레이스는 참가자 모두가 동일한 조건에서 레이스를 경험하고 경쟁할 수 있도록 운영하는 것을 기본 원칙으로 합니다. 따라서 부문별로 주최측이 지정한 의류와 신발을 반드시 착용해야 하며, 이를 통해 경기의 공정성과 대회 콘셉트의 일관성을 함께 확보하고자 합니다.': 'アウェイケン駅伝レースは、参加者全員が同一条件でレースを経験し競技できるよう運営することを基本原則としています。そのため、部門ごとに主催者が指定したウェアとシューズを必ず着用していただき、競技の公正性と大会コンセプトの一貫性をともに確保します。',
    '즉, 이번 대회는 단순한 자유 복장 러닝 이벤트가 아니라, 동일한 퍼포먼스 환경 안에서 레이스를 진행하는 것이 핵심 규정입니다.': 'つまり、本大会は単なる自由な服装のランニングイベントではなく、同一のパフォーマンス環境の中でレースを実施することが中核規定です。'
  }
};

const titleTranslations = {
  en: {
    '참가 안내 | 2026 데상트 어웨이큰 에키덴 레이스': 'Entry Guide | 2026 Descente Awaken Ekiden Race',
    '레이스 운영 | 2026 데상트 어웨이큰 에키덴 레이스': 'Race Operations | 2026 Descente Awaken Ekiden Race',
    '대회 코스 | 2026 데상트 어웨이큰 에키덴 레이스': 'Race Course | 2026 Descente Awaken Ekiden Race',
    '규정 | 2026 데상트 어웨이큰 에키덴 레이스': 'Rules | 2026 Descente Awaken Ekiden Race',
    '시간표 | 2026 데상트 어웨이큰 에키덴 레이스': 'Schedule | 2026 Descente Awaken Ekiden Race',
    '유의 사항 | 2026 데상트 어웨이큰 에키덴 레이스': 'Important Notes | 2026 Descente Awaken Ekiden Race',
    'DRC | 2026 데상트 어웨이큰 에키덴 레이스': 'DRC | 2026 Descente Awaken Ekiden Race',
    '대회 개요 | 2026 데상트 어웨이큰 에키덴 레이스': 'Overview | 2026 Descente Awaken Ekiden Race',
    '2026 데상트 어웨이큰 에키덴 레이스': '2026 Descente Awaken Ekiden Race'
  },
  ja: {
    '참가 안내 | 2026 데상트 어웨이큰 에키덴 레이스': 'エントリー案内 | 2026 デサント アウェイクン駅伝レース',
    '레이스 운영 | 2026 데상트 어웨이큰 에키덴 레이스': 'レース運営案内 | 2026 デサント アウェイクン駅伝レース',
    '대회 코스 | 2026 데상트 어웨이큰 에키덴 레이스': '大会コース | 2026 デサント アウェイクン駅伝レース',
    '규정 | 2026 데상트 어웨이큰 에키덴 레이스': 'レース規定 | 2026 デサント アウェイクン駅伝レース',
    '시간표 | 2026 데상트 어웨이큰 에키덴 레이스': 'スケジュール | 2026 デサント アウェイクン駅伝レース',
    '유의 사항 | 2026 데상트 어웨이큰 에키덴 레이스': '注意事項 | 2026 デサント アウェイクン駅伝レース',
    'DRC | 2026 데상트 어웨이큰 에키덴 레이스': 'DRC | 2026 デサント アウェイクン駅伝レース',
    '대회 개요 | 2026 데상트 어웨이큰 에키덴 레이스': '大会概要 | 2026 デサント アウェイクン駅伝レース',
    '2026 데상트 어웨이큰 에키덴 레이스': '2026 デサント アウェイクン駅伝レース'
  }
};

const normalizeI18nText = text => text.replace(/\s+/g, ' ').trim();
const textNodes = [];
const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
  acceptNode(node) {
    const value = normalizeI18nText(node.nodeValue);
    if (!value) return NodeFilter.FILTER_REJECT;
    const parent = node.parentElement;
    if (!parent || parent.closest('script, style')) return NodeFilter.FILTER_REJECT;
    return NodeFilter.FILTER_ACCEPT;
  }
});

while (walker.nextNode()) {
  const node = walker.currentNode;
  textNodes.push({ node, ko: normalizeI18nText(node.nodeValue) });
}

const originalTitle = document.title;
const htmlRoot = document.documentElement;
const menuButton = document.querySelector('.menu-toggle');
function getSavedLanguage() {
  try {
    return localStorage.getItem('site-language');
  } catch (error) {
    return null;
  }
}

function saveLanguage(lang) {
  try {
    localStorage.setItem('site-language', lang);
  } catch (error) {
    // Language switching still works for the current page if storage is unavailable.
  }
}

function setLanguage(lang) {
  const dictionary = translations[lang] || {};
  textNodes.forEach(({ node, ko }) => {
    node.nodeValue = lang === 'ko' ? ko : dictionary[ko] || ko;
  });

  document.title = lang === 'ko' ? originalTitle : titleTranslations[lang]?.[originalTitle] || originalTitle;
  htmlRoot.lang = lang;
  if (menuButton) {
    menuButton.setAttribute('aria-label', lang === 'en' ? 'Open menu' : lang === 'ja' ? 'メニューを開く' : '메뉴 열기');
  }

  document.querySelectorAll('.language-switcher button').forEach(button => {
    const isActive = button.dataset.lang === lang;
    button.classList.toggle('active', isActive);
    button.setAttribute('aria-pressed', String(isActive));
  });

  saveLanguage(lang);
}

document.querySelectorAll('.language-switcher button').forEach(button => {
  button.addEventListener('click', event => {
    event.stopPropagation();
    setLanguage(button.dataset.lang || 'ko');
  });
});

setLanguage(getSavedLanguage() || 'ko');
